### ISSUE TITLE
Possible issue with jansson tarball for Linux?

### ISSUE THREAD

**Issue by alexpreynolds** [bedops/bedops#125]
Error `bzip2: (stdin): trailing garbage after EOF ignored` shows up on Linux:

```
$ tar jtvf jansson-2.6.tar.bz2
...
-rw-r--r-- alexpreynolds/staff   1027 2014-02-10 23:53 jansson-2.6/cmake/config.h.cmake
-rw-r--r-- alexpreynolds/staff  14269 2014-02-10 22:31 jansson-2.6/cmake/FindSphinx.cmake

bzip2: (stdin): trailing garbage after EOF ignored
-rw-r--r-- alexpreynolds/staff   1707 2014-02-10 23:53 jansson-2.6/cmake/jansson_config.h.cmake
```

Using:

```
$ tar --version
tar (GNU tar) 1.23
```

This does not show up with OS X `tar`:

```
$ tar jtvf jansson-2.6.tar.bz2
...
-rw-r--r--  0 alexpreynolds staff   14269 Feb 10  2014 jansson-2.6/cmake/FindSphinx.cmake
-rw-r--r--  0 alexpreynolds staff    1707 Feb 10  2014 jansson-2.6/cmake/jansson_config.h.cmake
```

This uses a different version of `tar`:

```
$ tar --version
bsdtar 2.8.3 - libarchive 2.8.3
```

Maybe repackage the jansson tarball on Linux and push to branch?

**Comment by alexpreynolds** [comment]
I was not able to see problems with the jansson tarball with a newer version of GNU `tar` under OS X:

```
$ brew install gnu-tar
$ gtar --version
tar (GNU tar) 1.28
```

However, the same version of `tar` under Linux reports the same issues:

```
$ /usr/local/bin/tar --version
tar (GNU tar) 1.28
...
$ /usr/local/bin/tar jtvf jansson-2.6.tar.bz2
-rw-r--r-- alexpreynolds/staff   1027 2014-02-10 23:53 jansson-2.6/cmake/config.h.cmake
-rw-r--r-- alexpreynolds/staff  14269 2014-02-10 22:31 jansson-2.6/cmake/FindSphinx.cmake

bzip2: (stdin): trailing garbage after EOF ignored
-rw-r--r-- alexpreynolds/staff   1707 2014-02-10 23:53 jansson-2.6/cmake/jansson_config.h.cmake
```

Extracted tarball:

```
$ /usr/local/bin/tar jxvf jansson-2.6.tar.bz2 
...
jansson-2.6/doc/gettingstarted.rst

bzip2: (stdin): trailing garbage after EOF ignored
jansson-2.6/doc/github_commits.c
...
```

I took a look and nothing looked unusual about the RST file, assuming that the error message is flushed alongside the correct filename. 

I made a new tarball on the Linux host, which extracts without issue under GNU `tar` 1.23 and `bsdtar` 2.83 on Linux and OS X, resp. 

This new tarball was pushed to commit 1ce4669

**Comment by rekado** [comment]
The jansson tarball is in fact fine now, but the zlib and gzip2 tarballs also show this warning.  Could you please also update these tarballs?
