### ISSUE TITLE
bedops bug with starch input that includes a header

### ISSUE THREAD

**Issue by sjneph** [bedops/bedops#131]
starch files that have headers do not work with bedops unless they are piped in via unstarch:

```
> cat foo.bed
# header
chr1  1  10
```

```
> bedops --header -p foo.bed
```
works

```
> unstarch foo.starch | bedops --header -p -
```
works

```
> bedops --header -p foo.starch
```

does not.  Reported by Melissa at http://bedops.uwencode.org/forum/index.php?topic=94.msg223;boardseen#new

**Comment by alexpreynolds** [comment]
I added a patch to starchApi in branch v2p5p0 and commit e2fadc7

My limited testing suggests this helps, but I have some more inputs I want to test, probably later tomorrow. If you have time, please let me know if the patch fixes this for you, as well.

**Comment by alexpreynolds** [comment]
Potential patch in commit e2fadc74902eb5ce3655f87b8e6a7dc08aa5455a

Running tests that convert various BED > Starch > BED via BEDOPS calls.

**Comment by alexpreynolds** [comment]
Commit e6c7913 adds support for tabs in header lines. Provisional testing is done, but I want to run this on some larger inputs before publishing v2.4.9.
