### ISSUE TITLE
bedops / bedmap incompatible with some starch --gzip archives.

### ISSUE THREAD

**Issue by bgulko** [bedops/bedops#138]
Compressing a bed file with starch --gzip yields ancompressed file that can be decompressed with unstarch, but triggers an error in bedops and bedmap.

The bed file at 
   http://compgen.bscb.cornell.edu/~bgulko/assets/bedops/problem2/b2.bed
when compressed with 
>    starch --gzip b2.bed, 

yields the file at: 
   http://compgen.bscb.cornell.edu/~bgulko/assets/bedops/problem2/b2.bed.gzip.starch

This file can be decompressed with unstarch, without error. However, the command
>    bedops -m  b2.bed.gzip.starch | tail -3

Produces the error
>    May use bedops --help for more help.
    Error: ERROR: z-stream suffered data error
    chr1    86283991        86283992
    chr1    86285046        86285047
    chr1    86286446        86286447

Similar errors are encountered with bedmap.

A similar archive 
    http://compgen.bscb.cornell.edu/~bgulko/assets/bedops/problem2/b2.bed.bzip.starch
generated from the same source file, but using bzip compression via 
>    starch --bzip b2.bed

Does not exhibit this behavior.

The use of bzip is not a good workaround because bzip decompression takes about 3x as long in this pipeline.

This has been verified in bedops 2.4.11, 2.4.2, and 1.2.5

**Comment by alexpreynolds** [comment]
I'll see if I can reproduce this tomorrow. In the meantime, you should be able to pipe the output of `unstarch` to the standard input streams of`bedops` and `bedmap`. 

For example:

```
$ starch --gzip foo.bed > foo.starch
$ unstarch foo.starch | bedops -m - > foo.merged.bed
```

**Comment by bgulko** [comment]
Hi Alex. I certainly can, and appreciate the suggestion and quick response!

This  code is going to be performance critical. Using an uncompressed bed
file with --chrom is nearly as fast, or sometimes faster, then using
bedmap --chrom with a bzip starched archive (with >22 cores, 1 core
per chromosome).

I had hoped that --chrom with a starch/gzip archive would be on the
order of 2-3x faster, which would be significant for this application.

For now I'll go back to uncompressed bed files, but I'd love to try out
the gzip's version that would make more use of the indexing feature in
starch.

--Brad

**Comment by alexpreynolds** [comment]
Looks like there is a problem in the C++ code for extracting gzip streams. I still need to find the cause but will try to get a patch out soon. Thanks for the bug report.

**Comment by bgulko** [comment]
My pleasure, and thanks for tracking it down so quickly!

Its funny that it is triggered in bedmap/bedops but
somehow not in unstarch....

I'd love to get at the patch as soon as you have one,
starch/gzip seems to be at the sweet spot for my usage.
Enough compression to improve IO and fast enough to be
an improvement over streaming the uncompressed data.

--Brad

**Comment by alexpreynolds** [comment]
The starch and unstarch tools are written with different code from what bedops and bedmap etc. use. 

I think I know what the problem is, but I need to think a bit more on a decent solution. Hopefully it won't take long to get you something working.

**Comment by alexpreynolds** [comment]
Sorry for the delay. I have patched the code that ``bedops`` and other core tools use to extract ``zlib``-compressed Starch files.

I'll be doing a little more testing before putting out a "final" release, probably later tonight or early tomorrow, but if you are pressed for time and want to try this out now, you can grab this patch in the ``v2p4p12`` branch:

```
$ pwd
/foo/bar/baz/github_stuff/bedops
$ git checkout master
$ git pull origin master
$ git fetch
$ git checkout v2p4p12
$ git branch
** just to make sure you're in the v2p4p12 branch **
```

Then to compile and install to a local ``bin`` directory:

```
$ make
$ make install
```

To test `/tmp/b2.bed`, for example:

```
$ ./bin/starch --gzip /tmp/b2.bed > /tmp/b2.gzstarch
$ ./bin/unstarch /tmp/b2.gzstarch | diff -s - /tmp/b2.bed
Files - and /tmp/b2.bed are identical
$ ./bin/bedops -u /tmp/b2.gzstarch | diff -s - /tmp/b2.bed
Files - and /tmp/b2.bed are identical
```

A final release with associated binaries should be coming soon, once some more tests are done.

Thanks again for your bug report and patience.

**Comment by alexpreynolds** [comment]
Patched in commit 3887d1ed4f4fcf6433ce0d07d6d2c58a14c03f17

**Comment by bgulko** [comment]
I just wanted to send a personal thanks for
getting on this so quickly. It will make a difference
in my work and I really really appreciate it!

-Brad

**Comment by bedops** [comment]
You're welcome!
