### ISSUE TITLE
bedops produces incorrect output with --gzip starch archive. V2.4.14

### ISSUE THREAD

**Issue by bgulko** [bedops/bedops#145]
Using starched archive at http://genome-mirror.cshl.edu/~bgulko/assets/bedops/problem3/a.starch
> unstarch a.starch | head
chr1    15167   15168   0.860
chr1    15168   15169   0.860
chr1    15169   15170   0.860
chr1    15170   15171   0.860
chr1    15171   15172   0.860
chr1    15172   15173   0.860

Which is expected. However,
> bedops -u a.starch | head

(▒|     0       0       0.930
(▒|     0       0       0.930
(▒|     0       0       0.930
(▒|     0       0       0.930
(▒|     166     166     1.000
chr1    166     166     1.000
chr1    166     166     1.000
chr1    166     166     1.000
chr1    166     166     1.000
chr1    166     166     1.000

( the unprintable control characters are produced by bedops)

> bedops  -u a.starch | head -2 | od -ba
0000000 050 251 174 011 060 011 060 011 060 056 071 063 060 012 050 251
          (   )   |  ht   0  ht   0  ht   0   .   9   3   0  nl   (   )
0000020 174 011 060 011 060 011 060 056 071 063 060 012
          |  ht   0  ht   0  ht   0   .   9   3   0  nl

I've seen this with several, recently created, starch archives all using >= v2.4.12 .

Note this sample starch archive < 1MB, and is the smallest subset of a larger starch file exhibiting this problem that I could conveniently provide.

-- Brad

**Comment by bgulko** [comment]
Linux (x64) binary distribution of bedops. -- Brad

**Comment by sjneph** [comment]
I'm unable to reproduce the problem using the sample above with v2.4.14 of things.  bedops -u works with starch files that are produced with v2.4.14 when I test.  I tested things built from source and from the current downloads (Linux 64-bit).  Can you think of anything else that might help us to reproduce the problem?

**Comment by bgulko** [comment]
I created the starch archive with V2.4.14. I just recreated the archive to be sure using
> unstarch a.starch | starch --gzip > b.starch

and the new archive is the same size and demonstrates the same behavior.
I checked all the version numbers to make sure I was using V2.4.14 .

When I do the same thing using --bzip compression, I do not get this problem, so it seems likely that this is related to the use of the --gzip libraries. Are any of these dynamically loaded?

**Comment by bgulko** [comment]
I also tried
> unstarch a.starch > a.bed
starch --gzip a.bed > b.bed.starch

and regenerated the same problem. The resultant output I am seeing from
> bedops -u a.starch > a.bad

is available at 
http://genome-mirror.cshl.edu/~bgulko/assets/bedops/problem3/a.bad

**Comment by bedops** [comment]
Hi Brad,

I'm sorry you are running into trouble again. I'll see if I can reproduce the issue here. In the meantime, can you please let me know what type and version of Linux you are running? Bzip2 and zlib are static libraries but I compile the prebuilt binaries under a new-ish kernel.

-Alex

**Comment by bgulko** [comment]
Me too. Thanks! I'm used to this stuff being rock solid, so I am always surprised when I run into an issue. The version of Linux on our server is 
> uname -r
2.6.32-504.el6.x86_64

or 

> lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.6 (Santiago)
Release:        6.6
Codename:       Santiago

**Comment by alexpreynolds** [comment]
Hi Brad,

Something seems to be wrong, still. I will investigate when I get back to
work later this week. I apologize for the trouble and thanks for the bug
report.

Regards,
Alex

**Comment by bgulko** [comment]
Just a ping. Any update on this one?

**Comment by alexpreynolds** [comment]
I apologize, but I have not yet been able to push an update. I hope to have
time this week, however.

**Comment by bgulko** [comment]
Hi Alex,

Sorry to be such a pain, but I'm still getting bitten by this
one in 2.4.14. Anything New?

--Brad

**Comment by alexpreynolds** [comment]
Some other projects have had to take higher priority. It's on my mind and I am hoping I can put in time this week to work on this.

**Comment by alexpreynolds** [comment]
Patched in 8393d029d6795c8a4a6317c929fe8b68aa80e555
