### ISSUE TITLE
add support for bedpe data

### ISSUE THREAD

**Issue by crazyhottommy** [bedops/bedops#150]
Hi,

Thanks for such a nice tool and detailed documentation. 
I am working on some data which are in [bedpe format](http://bedtools.readthedocs.org/en/latest/content/general-usage.html#bedpe-format) 
I am now using bedtools pairtopair to find the intersections of both ends.

I have a lot of them and want to do the intersections. as mentioned by you in this post https://www.biostars.org/p/13516/
when one has a lot of such files, it is not efficient to do the intersections for bed files using bedtools.
bedops can do a better job in this.

I am wondering if you can add some support for bedpe data and for multi-bedpe files to be intersected.

Thanks,
Ming

**Comment by sjneph** [comment]
Hi Ming,
Can you give a concrete example using your data?

This isn't an answer necessarily.  If you think about a viable tag, it has
to come from some location in the genome.  The PE format allows ends to
come from different chromosomes, and that's probably not real unless there
are rearrangements, and the genome sequenced is quite different from the
reference genome.  Unless you are working with something not typical,
chances are good that a PE read that is tens of thousands of nt long is
junk, and the the same is true for reads that include different
chromosomes.  It isn't impossible that you use multiple coordinates to
encode information about a genomic feature and that PE fits the bill, but
that probably is unlikely.  So, let me assume for the moment that you are
working with PE sequencing reads and that you would want to throw out tags
that are not viable.

From the link you give, they have this example:

chr1 10 20 chr5 50 60 a1 30 + - 0 1
chr9 30 40 chr9 80 90 a2 100 + - 2 1

At first glance, I would:
awk '$1 == $4 && $6-$2 < 1000' input.bed.pe \
  | awk '{ print $1, $2, $6, $0 }' \
  | sort-bed - \
 > fileA.bed

All of the original columns are still intact at column 4 and beyond.
Columns 1-3 show the extent of the feature.  If this captures what you are
interested in, then you now have a BED-like file that is ready for any
operation with BEDOPS, including intersections with bedops using any number
of input files.

Shane

**Comment by crazyhottommy** [comment]
Hi Shane,

Thanks for your detailed reply. Let me phrase what I want to do below.

I called some structural variants and I convert the vcf format into bedpe (contain info for the two breakends). see [here](http://software.10xgenomics.com/docs/pipelines/output/bedpe). And for translocations, I will have intervals on different chromosomes.

I have 50 such bedpe files. one simple question I want to ask is that if there are any recurrent structural variants. So, if both ends of a row in bedpe file overlap with another row in another bedpe file, I will count it as a recurrent structural variants.

I am relatively familiar with linux commands, know some R and python. I just wander if there is an existing tool for it. I do not want to re-invent the wheel.
Or if you can suggest a work-around for me?

Thanks very much,
Ming

**Comment by sjneph** [comment]
Here is a c-shell script that might be useful as a starting point.

If you start with an unsorted input.bedpe:
chr1 1 24 chr5 200 300 id-1
chr2 23 200 chr2 400 500 id-2
chr3 44 50 chr7 1 990 id-3
chr1 3 20 chr5 201 301 id-4
chr1 4 5 chr1 700 800 id-5
chr1 17 18 chr5 202 203 id-6

and you run (BEDOPS tools in your PATH):
> ok.csh input.bedpe

you get back:
chr1    1   24  chr5    200 300 id-1    id-1;id-4;id-6
chr1    3   20  chr5    201 301 id-4    id-4;id-1;id-6
chr1    17  18  chr5    202 203 id-6    id-6;id-1;id-4


The last awk statement is kind of icky.  Everything else is simple.  I'd
recommend replacing the awk statement with a 'head' statement to see what
the output of the simpler commands look like.  There are various ways that
you might slice up those results.  My objective was to map on the unique
row IDs as the answer.  That may not be what you want.  Using unix 'join'
on unique id's is powerful, and that's what I'd use to map coordinate info
onto IDs if needed.  But, you'd have to munge the results a bit more for
all of that.

Shane

**Comment by crazyhottommy** [comment]
Hi Shane,

Thanks very much! I did not see your shell script though.
I am comfortable with awk and sort of familiar with join, paste and many other useful tools.
I can munge the results myself. see a [post](http://crazyhottommy.blogspot.com/2015/08/linux-command-join-with-header.html) by me :)

Ming

**Comment by sjneph** [comment]
awk 'BEGIN {OFS="\t"} ; { \


      print $1, $2, $3, $7; \


      print $4, $5, $6, $7 \


    }' input.bedpe \


  | sort-bed - \


  | bedmap --echo --echo-ref-name --echo-map-id-uniq --delim "\t" - \


  | sort -sk4,4 \


  | awk 'BEGIN {OFS="\t"} ; { \


      if ( NR % 2 == 1 ) { \


        a=$1"\t"$2"\t"$3; \


        lng=split($6, arr, ";"); \


        delete brr; \


        for ( i in arr ) { \


          brr[arr[i]]; \


        } \


      } else { \


        lng=split($6, arr, ";"); \


        ok=$4; \


        for ( i in arr ) { \


          if ( arr[i] in brr ) { \


            if ( arr[i] != $4 ) { \


              ok=ok";"arr[i] \


            } \


          } \


        } \


        if ( ok != $4 ) { \


          print a, $1, $2, $3, $4, ok \


        } \


      } \


    }'

**Comment by sjneph** [comment]
Ok, try this one.

[ok.txt](https://github.com/bedops/bedops/files/11052/ok.txt)

**Comment by sjneph** [comment]
Here, you can try this one.

[ok.txt](https://github.com/bedops/bedops/files/11055/ok.txt)

**Comment by crazyhottommy** [comment]
Thanks, it worked for your example. I will see how to use it for my purpose.

**Comment by crazyhottommy** [comment]
If I have strandness (+ -) on my 9th and 10th column. Does Bedops take that into consideration?

**Comment by sjneph** [comment]
No.  Strandedness adds operation-specific ugliness so we just partition the data.  It's a bit more hassle with this paired data stuff, unfortunately.  Typically, assuming strand info is in column 6, I suggest:
> awk '$6 == "+"' input.bed > input.pos.bed
> awk '$6 == "-"' input.bed > input.neg.bed

Then, operate on them separately.  Things can always be glued back together efficiently with bedops -u.  The suite tries to resist feature bloat.  Sometimes, it makes life a bit harder; most of the time, it keeps things tidy and fast.  With strandedness, various operations/utilities have dubious possibilities so we decided against it.  Usually, it's simple to just partition the data as above.  In your case, there are 4 possibilities.

**Comment by crazyhottommy** [comment]
Thanks! I found this also http://bedops.uwencode.org/forum/index.php?PHPSESSID=op66olfeqctbgkrnu9neq4vsu3&topic=14.msg26#msg26

**Comment by sjneph** [comment]
Okay, I'm closing this one out.  Feel free to re-open or ask questions on our forum if you like.
