### ISSUE TITLE
bug when starching a file with --gzip

### ISSUE THREAD

**Issue by sjneph** [bedops/bedops#151]
starch --gzip big-file.bed > big-file.gzip.starch

is missing entire chromosomes, while
starch big-file.bed > big-file.bzip2.starch
is not.

I haven't reproduced this on a small scale yet.  Example files with the problem, and more detailed explanation is available at:
http://www.uwencode.org/proj/sneph/bedops-debug-files/bedops-bugs.html

**Comment by alexpreynolds** [comment]
Thanks for the details. Will investigate soon.

**Comment by sjneph** [comment]
Thanks.  I've linked up the full file from what the pipeline would produce (no starching, then unstarching).

**Comment by sjneph** [comment]
Alex found that my claim is false.  There is no problem with starch --gzip or reading such a file through other BEDOPS utils.

**Comment by alexpreynolds** [comment]
(Well, there is still an open bug with gzip that I need to review, but I'm
not sure it is related to this.)
