### ISSUE TITLE
EasyBuild compilation failure

### ISSUE THREAD

**Issue by verdurin** [bedops/bedops#155]
I'm trying to build using EasyBuild, on a Fedora 23 host.

I see the following error:

```
checking for gcc... gcc
gcc -O2 -march=native  -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -I/home/adam/.local/easybuild/software/OpenBLAS/0.2.15-GCC-4.9.3-2.25-LAPACK-3.6.0/include -I/home/adam/.local/easybuild/software/ScaLAPACK/2.0
.2-gompi-2016a-OpenBLAS-0.2.15-LAPACK-3.6.0/include -I/home/adam/.local/easybuild/software/FFTW/3.3.4-gompi-2016a/include  -c -o adler32.o adler32.c
checking whether the C compiler works... no
configure: error: in `/home/adam/.local/easybuild/build/BEDOPS/2.4.19/foss-2016a/bedops-2.4.19/third-party/jansson-2.6':
configure: error: C compiler cannot create executables
See `config.log' for more details
system.mk/Makefile.linux:158: recipe for target 'third-party/jansson/lib/libjansson.a' failed
make[1]: *** [third-party/jansson/lib/libjansson.a] Error 77
make[1]: *** Waiting for unfinished jobs....
```

Here's the relevant part from `config.log`:

```
configure:3174: $? = 0
configure:3163: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/home/adam/.local/easybuild/software/GCCcore/4.9.3/libexec/gcc/x86_64-unknown-linux-gnu/4.9.3/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../configure --enable-languages=c,c++,fortran --enable-lto --enable-checking=release --disable-multilib --enable-shared=yes --enable-static=yes --enable-threads=posix --enable-gold=defaul
t --enable-plugins --enable-ld --with-plugin-ld=ld.gold --enable-bootstrap --prefix=/home/adam/.local/easybuild/software/GCCcore/4.9.3 --with-local-prefix=/home/adam/.local/easybuild/software/GCCcore/4.9.
3
Thread model: posix
gcc version 4.9.3 (GCC)
configure:3174: $? = 0
configure:3163: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3174: $? = 1
configure:3163: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:3174: $? = 1
configure:3194: checking whether the C compiler works
configure:3216: gcc -O2 -march=native -I/home/adam/.local/easybuild/software/OpenBLAS/0.2.15-GCC-4.9.3-2.25-LAPACK-3.6.0/include -I/home/adam/.local/easybuild/software/ScaLAPACK/2.0.2-gompi-2016a-OpenBLAS
-0.2.15-LAPACK-3.6.0/include -I/home/adam/.local/easybuild/software/FFTW/3.3.4-gompi-2016a/include -L/home/adam/.local/easybuild/software/GCCcore/4.9.3/lib64 -L/home/adam/.local/easybuild/software/GCCcore
/4.9.3/lib -L/home/adam/.local/easybuild/software/OpenBLAS/0.2.15-GCC-4.9.3-2.25-LAPACK-3.6.0/lib -L/home/adam/.local/easybuild/software/ScaLAPACK/2.0.2-gompi-2016a-OpenBLAS-0.2.15-LAPACK-3.6.0/lib -L/hom
e/adam/.local/easybuild/software/FFTW/3.3.4-gompi-2016a/lib conftest.c third-party/jansson/lib/libjansson.a third-party/bzip2/libbz2.a third-party/zlib/libz.a >&5
gcc: error: third-party/jansson/lib/libjansson.a: No such file or directory
gcc: error: third-party/bzip2/libbz2.a: No such file or directory
gcc: error: third-party/zlib/libz.a: No such file or directory
configure:3220: $? = 1
configure:3258: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "jansson"
| #define PACKAGE_TARNAME "jansson"
| #define PACKAGE_VERSION "2.6"
| #define PACKAGE_STRING "jansson 2.6"
| #define PACKAGE_BUGREPORT "petri@digip.org"
| #define PACKAGE_URL ""
| #define PACKAGE "jansson"
| #define VERSION "2.6"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:3263: error: in `/home/adam/.local/easybuild/build/BEDOPS/2.4.19/foss-2016a/bedops-2.4.19/third-party/jansson-2.6':
configure:3265: error: C compiler cannot create executables
See `config.log' for more details
```

**Comment by alexpreynolds** [comment]
I installed a stock Fedora 23 Workstation via the Live CD here: https://getfedora.org/workstation/download/ to a VM in VirtualBox (5.0.20 r106931):

```
$ cat /etc/fedora-release
Fedora release 23 (Twenty Three)
```

After setting up GCC and static libraries per installation instructions, I was able to compile and install BEDOPS 2.4.19 without errors.

For compilation and install instructions, please see: https://bedops.readthedocs.io/en/latest/content/installation.html#installation-via-source-code

**Comment by verdurin** [comment]
That works for me too,  but the important fact here is that I'm trying to build `BEDOPS` for `EasyBuild`, to have a packaged and reproducible environment.

Really, the problem here is the bundling of the libraries, and in particular the bundling of libraries as tarballs, which means I can't even use a patch to remove the problematic invocation of GCC.

**Comment by verdurin** [comment]
This relates in part to #128, I believe.

**Comment by alexpreynolds** [comment]
To my recollection, there are no changes to the Jansson build scripts within the tarball. The only customization to the build process is for OS X hosts, where there are changes to the `-arch` and `-build` parameters for the platform-specific master Makefile, which creates architecture-specific libraries. 

For the Linux platform, I reviewed the system-level BEDOPS Makefile and — other than setting a custom `prefix` so that the library goes somewhere useful — there are no architecture-specific or other changes to how Jansson gets built. It is functionally equivalent to the usual `configure && make && make install` process for building most tools.

It also looks like the stock build that I ran under Fedora 23 went to completion, which seems to confirm that a stock build works correctly.

Perhaps EasyBuild is changing the build environment and causing Jansson compilation to fail by passing problematic flags or settings. For example, a typical run of the Homebrew package manager tool makes global changes to the `CFLAGS` and `CXXFLAGS` variables and optimization level in such a way that causes a typical build to fail on OS X. Therefore, I had to set up the `bedops.rb` recipe to disable those customizations and use what the OS X-specific Makefile uses.

I can see if I can find time to learn EasyBuild and find out what variables it is changing that could break the build process (and see what could be disabled, if possible) but if you're interested, I would suggest starting there. Perhaps there is an EasyBuild script that already exists for Jansson, which might suggest what is being changed that would cause problems for that library.

Another possibility is upgrading the Jansson code this project uses, to go from v2.6 to v2.7, but the change logs for that project do not suggest that its patches have much relevance to issues with being built by EasyBuild.

**Comment by alexpreynolds** [comment]
For instance, it looks like EasyBuild makes the following changes to the build environment, at least:

http://easybuild.readthedocs.io/en/latest/Controlling_compiler_optimization_flags.html

Not sure if any one of those changes are causing problems, but I would perhaps start exploring there.

**Comment by boegel** [comment]
EasyBuild indeed sets up the build environment. In particular, it defines the environment as follows, in this particular case (for example, some specific values depends on the install path of the dependencies):

```
  export BLAS_INC_DIR="/prefix/software/OpenBLAS/0.2.15-GCC-4.9.3-2.25-LAPACK-3.6.0/include"
  export BLAS_LAPACK_INC_DIR="/prefix/software/OpenBLAS/0.2.15-GCC-4.9.3-2.25-LAPACK-3.6.0/include"
  export BLAS_LAPACK_LIB_DIR="/prefix/software/OpenBLAS/0.2.15-GCC-4.9.3-2.25-LAPACK-3.6.0/lib"
  export BLAS_LAPACK_MT_STATIC_LIBS="libopenblas.a,libgfortran.a"
  export BLAS_LAPACK_STATIC_LIBS="libopenblas.a,libgfortran.a"
  export BLAS_LIB_DIR="/prefix/software/OpenBLAS/0.2.15-GCC-4.9.3-2.25-LAPACK-3.6.0/lib"
  export BLAS_MT_STATIC_LIBS="libopenblas.a,libgfortran.a"
  export BLAS_STATIC_LIBS="libopenblas.a,libgfortran.a"
  export CC="gcc"
  export CFLAGS="-O2 -march=native"
  export CPPFLAGS="-I/prefix/software/OpenBLAS/0.2.15-GCC-4.9.3-2.25-LAPACK-3.6.0/include -I/prefix/software/ScaLAPACK/2.0.2-gompi-2016a-OpenBLAS-0.2.15-LAPACK-3.6.0/include -I/prefix/software/FFTW/3.3.4-gompi-2
016a/include"
  export CXX="g++"
  export CXXFLAGS="-O2 -march=native"
  export F77="gfortran"
  export F90="gfortran"
  export F90FLAGS="-O2 -march=native"
  export FC="gfortran"
  export FCFLAGS="-O2 -march=native"
  export FFLAGS="-O2 -march=native"
  export FFTW_INC_DIR="/prefix/software/FFTW/3.3.4-gompi-2016a/include"
  export FFTW_LIB_DIR="/prefix/software/FFTW/3.3.4-gompi-2016a/lib"
  export FFTW_STATIC_LIBS="libfftw3.a"
  export FFT_INC_DIR="/prefix/software/FFTW/3.3.4-gompi-2016a/include"
  export FFT_LIB_DIR="/prefix/software/FFTW/3.3.4-gompi-2016a/lib"
  export FFT_STATIC_LIBS="libfftw3.a"
  export FLIBS="-lgfortran"
  export LAPACK_INC_DIR="/prefix/software/OpenBLAS/0.2.15-GCC-4.9.3-2.25-LAPACK-3.6.0/include"
  export LAPACK_LIB_DIR="/prefix/software/OpenBLAS/0.2.15-GCC-4.9.3-2.25-LAPACK-3.6.0/lib"
  export LAPACK_MT_STATIC_LIBS="libopenblas.a,libgfortran.a"
  export LAPACK_STATIC_LIBS="libopenblas.a,libgfortran.a"
  export LDFLAGS="-L/prefix/software/GCCcore/4.9.3/lib64 -L/prefix/software/GCCcore/4.9.3/lib -L/prefix/software/OpenBLAS/0.2.15-GCC-4.9.3-2.25-LAPACK-3.6.0/lib -L/prefix/software/ScaLAPACK/2.0.2-gompi-2016a-OpenBLAS-0.2.15-LAPACK-3.6.0/lib -L/prefix/software/FFTW/3.3.4-gompi-2016a/lib"
  export LIBBLAS="-lopenblas -lgfortran"
  export LIBBLAS_MT="-lopenblas -lgfortran"
  export LIBFFT="-lfftw3"
  export LIBLAPACK="-lopenblas -lgfortran"
  export LIBLAPACK_MT="-lopenblas -lgfortran"
  export LIBLAPACK_MT_ONLY="-lopenblas -lgfortran"
  export LIBLAPACK_ONLY="-lopenblas -lgfortran"
  export LIBS="-lm -lpthread"
  export LIBSCALAPACK="-lscalapack -lopenblas -lgfortran"
  export LIBSCALAPACK_MT="-lscalapack -lopenblas -lpthread -lgfortran"
  export LIBSCALAPACK_MT_ONLY="-lscalapack -lgfortran"
  export LIBSCALAPACK_ONLY="-lscalapack -lgfortran"
  export MPICC="mpicc"
  export MPICXX="mpicxx"
  export MPIF77="mpifort"
  export MPIF90="mpifort"
  export MPIFC="mpifort"
  export MPI_INC_DIR="/prefix/software/OpenMPI/1.10.2-GCC-4.9.3-2.25/include"
  export MPI_LIB_DIR="/prefix/software/OpenMPI/1.10.2-GCC-4.9.3-2.25/lib"
  export MPI_LIB_SHARED="/prefix/software/OpenMPI/1.10.2-GCC-4.9.3-2.25/lib/libmpi.so"
  export MPI_LIB_STATIC=""
  export OMPI_CC="gcc"
  export OMPI_CXX="g++"
  export OMPI_F77="gfortran"
  export OMPI_F90="gfortran"
  export OMPI_FC="gfortran"
  export OPTFLAGS="-O2 -march=native"
  export PRECFLAGS=""
  export SCALAPACK_INC_DIR="/prefix/software/ScaLAPACK/2.0.2-gompi-2016a-OpenBLAS-0.2.15-LAPACK-3.6.0/include"
  export SCALAPACK_LIB_DIR="/prefix/software/ScaLAPACK/2.0.2-gompi-2016a-OpenBLAS-0.2.15-LAPACK-3.6.0/lib"
  export SCALAPACK_MT_STATIC_LIBS="libscalapack.a,libopenblas.a,libgfortran.a,libpthread.a"
  export SCALAPACK_STATIC_LIBS="libscalapack.a,libopenblas.a,libgfortran.a"
```

In addition, variables like `$LIBRARY_PATH`, `$LD_LIBRARY_PATH`, `$CPATH`, etc are also update for the dependencies being loaded.

Hope this helps...

**Comment by alexpreynolds** [comment]
That list looks like an excellent place to start debugging to see which EasyBuild setting is breaking the build. Perhaps disable all changes and start adding them back in one by one?

**Comment by verdurin** [comment]
Looks like it's this one that breaks the `jansson` compilation:

```
export LIBS="-lm -lpthread"
```

**Comment by verdurin** [comment]
Okay, by unsetting `LIBS` I've managed to complete a build.

However, the following binaries all dump core: `bedextract`, `bedmap`, `bedops` and `closest-features`, and I've had enough for today.

**Comment by alexpreynolds** [comment]
I dug around and the conversion tool Makefiles use `${PWD}` instead of `${CURDIR}`, which might affect [recursive](https://www.gnu.org/software/make/manual/html_node/Recursion.html) calls to GNU `make`. 

I doubt that's related to your issue, but I set up a v2.4.20 branch in case you find something else that we can fix (other than eliminating the step of building static libraries from Jansson and the compression libraries).

**Comment by timeu** [comment]
We have the same issue. 
I tried to compile Bedops without the third party libs (zlib, bzip2 and jansson) because they are available as dependencies in our easybuild environment, but I get following error (I guess due to the patched zlib library): 

```
../../../../interfaces/src/data/starch/starchFileHelpers.c:181:83: error: ‘deflateInit2cpp’ was not declared in this scope                                                                                                                                                         
     ret = deflateInit2cpp(&strm, level, Z_DEFLATED, (15+16), 8, Z_DEFAULT_STRATEGY); 
```

**Comment by alexpreynolds** [comment]
Until there is a fix in EasyBuild that doesn't alter the build environment, I recommend using the usual `make` process described in our instructions. I just don't know enough EasyBuild to figure out what is going wrong during the build.

**Comment by boegel** [comment]
@alexpreynolds altering the build environment is one of the main features of EasyBuild, it's not a bug... :-)

@verdurin has figured out that bedops doesn't like the value of `$LIBS` as defined by EasyBuild, which is fine, it's trivial to make EasyBuild undefine `LIBS` before running make, by including this in the easyconfig file used for bedops:

```
prebuildopts = "unset LIBS && "
```

However, that doesn't explain why several of the binaries are crashing. Did you look into that further @verdurin?

**Comment by verdurin** [comment]
@boegel - under pressure of time, I built a temporary RPM instead, which doesn't crash. Will get back to the crashes with the EasyBuild version when I can.

**Comment by alexpreynolds** [comment]
You might perhaps check and unset other variables that overwrite what is in the existing Makefiles, like CFLAGS etc. Looking at the list of variables that EasyBuild sets, it looks like a lot of libraries and headers are referenced that serve no purpose for this toolkit.

**Comment by SethosII** [comment]
Has anyone news on this? I also tried to build `BEDOPS` from source with `EasyBuild` but I got the same issue with jansson during the build. `prebuildopts = "unset LIBS && "` works for me and the generated binaries don't crash instantly. So is this the way to go?

**Comment by alexpreynolds** [comment]
It looks like this package manager changes the build environment in ways we don't control. I doubt there is much that we can do to help. I would suggest contacting the EasyBuild developers for support.
