### ISSUE TITLE
sort-bed does not work as expected on bedGraph files

### ISSUE THREAD

**Issue by c-guzman** [bedops/bedops#156]
For some reason when I attempt to sort-bed my bedGraph files my chromosome names are converted to a weird annotation of G********* and the file type changes from text to video.

Using Linux Ubuntu 14.04. Latest conda version of bedops.

**Comment by alexpreynolds** [comment]
Can you post your bedGraph file somewhere accessible? We can try sorting it here and see if we get the same result.

**Comment by alexpreynolds** [comment]
Any update? If things are still not working, please feel free to let us know.

**Comment by alexpreynolds** [comment]
If you have a test input we can run on this end, feel free to update this ticket.
