### ISSUE TITLE
Weird gene_id field in gtf2bed output on gtf from iGenome

### ISSUE THREAD

**Issue by blaiseli** [bedops/bedops#158]
I tried to use `gtf2bed` (version 2.4.19) to convert a gtf file obtained from illumina's iGenome set of annotations, originally from Ensembl: <ftp://igenome:G3nom3s4u@ussd-ftp.illumina.com/Caenorhabditis_elegans/Ensembl/WBcel235/Caenorhabditis_elegans_Ensembl_WBcel235.tar.gz>

I'd imagine that these  sources were reliable in terms of format compliance.

However, this gtf file seems to cause parsing problems for `gtf2bed`.

Here is the original fist line:

    I	ensembl	exon	3747	3909	.	-	.	exon_id "WBGene00023193.e1"; exon_number "1"; exon_version "1"; gene_biotype "snoRNA"; gene_id "WBGene00023193"; gene_name "Y74C9A.6"; gene_source "ensembl"; gene_version "1"; transcript_biotype "snoRNA"; transcript_id "Y74C9A.6"; transcript_name "Y74C9A.6"; transcript_source "ensembl"; transcript_version "1"; tss_id "TSS18840";

And here is its conversion:

    I	3746	3909	"WBGene00023193	.	-	ensembl	exon	.	exon_id "WBGene00023193.e1"; exon_number "1"; exon_version "1"; gene_biotype "snoRNA"; gene_id "WBGene00023193"; gene_name "Y74C9A.6"; gene_source "ensembl"; gene_version "1"; transcript_biotype "snoRNA"; transcript_id "Y74C9A.6"; transcript_name "Y74C9A.6"; transcript_source "ensembl"; transcript_version "1"; tss_id "TSS18840";

I ran the gtf validator I found on <http://mblab.wustl.edu/software.html>, and the final results are:
```
Warnings encountered:
Count	Description
107800	Illegal value for <feature> field.  Should be 'CDS', 'exon', 'start_codon', or 'stop_codon'.
26895	Transcript contains no CDS features.
2	Transcript has no start codon.
12	Transcript has no stop codon.
64	Stop codon location inconsistent with terminal exon location.
41	Complete transcript length not multiple of 3.
41	Inconsistant phase value accross transcript.
41	Stop codon included in terminal CDS.
8	Transcript contains short (<20bp) intron(s).

Statistics:
	46748 genes with 57834 transcripts containing 202766 cds.
Bad Genes:
```

There are warnings, but no errors.

Is it really invalid gtf?

**Comment by alexpreynolds** [comment]
No, there is a bug in GTF conversion when the gene ID is not processed correctly if it is not positioned at the start of the attributes field. I added some code for making this parsing more stringent in commit a8e0a3a of branch v2p4p20. 

I'll probably push out a master release in a day or two. You can grab the v2p4p20 branch now, if you need a working parser sooner rather than later.
