### ISSUE TITLE
Uninstallation of the Bedops

### ISSUE THREAD

**Issue by mortunco** [bedops/bedops#159]
Hi,

I would like to remove bedops from my local because I actually wanted to download it through home-brew. I see that my ```which bedops``` turns ```/usr/local/bin/bedops``` I dont know which functions are belong to bedops. 

Is there a way to uninstall it from the machine ?

/usr/local/bin is ahead of my homebrew path so because of the bedops in the initial location, my machine cannot run home-brew version. Thanks for creating this great suit.

Thanks in advance,

Tunc.

**Comment by ozturan** [comment]
Yeah I'm having the same problem.

**Comment by alexpreynolds** [comment]
No warranties implied or expressed, but I think the following script should help. 

```
#!/bin/sh

rm -f /usr/local/bin/bedextract
rm -f /usr/local/bin/bedmap
rm -f /usr/local/bin/bedops
rm -f /usr/local/bin/closest-features
rm -f /usr/local/bin/sort-bed
rm -f /usr/local/bin/starch
rm -f /usr/local/bin/starchcat
rm -f /usr/local/bin/unstarch
rm -f /usr/local/bin/starchcluster_sge
rm -f /usr/local/bin/starchcluster_gnuParallel
rm -f /usr/local/bin/bam2bed
rm -f /usr/local/bin/bam2starch
rm -f /usr/local/bin/bam2bed_sge
rm -f /usr/local/bin/bam2starch_sge
rm -f /usr/local/bin/bam2bed_gnuParallel
rm -f /usr/local/bin/bam2starch_gnuParallel
rm -f /usr/local/bin/gff2bed
rm -f /usr/local/bin/gff2starch
rm -f /usr/local/bin/gtf2bed
rm -f /usr/local/bin/gtf2starch
rm -f /usr/local/bin/gvf2bed
rm -f /usr/local/bin/gvf2starch
rm -f /usr/local/bin/psl2bed
rm -f /usr/local/bin/psl2starch
rm -f /usr/local/bin/rmsk2bed
rm -f /usr/local/bin/rmsk2starch
rm -f /usr/local/bin/sam2bed
rm -f /usr/local/bin/sam2starch
rm -f /usr/local/bin/vcf2bed
rm -f /usr/local/bin/vcf2starch
rm -f /usr/local/bin/wig2bed
rm -f /usr/local/bin/wig2starch
rm -f /usr/local/bin/convert2bed
```

Copy and paste that to a text file, `chmod ugo+x` the file, and then run it to remove BEDOPS from `/usr/local/bin`.

I'll try to work in a more formal uninstaller in a future release.

**Comment by anandksrao** [comment]
Also, 
`rm -f *float128 *megarow *typical`
it appears
