### ISSUE TITLE
convert2bed can't write to stdout

### ISSUE THREAD

**Issue by mojaveazure** [bedops/bedops#166]
Hello,

I'm trying to use `convert2bed` to change a VCF to BED file, but I'm getting the following error:

```bash
$ convert2bed --input=vcf < my.vcf
Unknown problem creating directory.  Check permissions.  
Error: Stage [Sorted BED to stdout] failed -- exit status [256 | 1]
```

I get this error when I redirect the output to a file

I'm using BEDOPS 2.4.20 on 64-bit Ubuntu 16.04 LTS. I'm using the 64-bit binarie provided on the releases page

**Comment by alexpreynolds** [comment]
There is a program called `sort-bed` that is used to ensure that the BED output from `convert2bed` is in correct sort order. 

It attempts to create a temporary folder to store intermediate sort results, and this attempt can fail if you do not have permissions to write to your host's `/tmp` folder.

You could use the `--sort-tmpdir` option with `convert2bed` to set a different directory:

```
$ convert2bed --help
...
--sort-tmpdir=<dir> (-r <dir>)
      Optionally sets [dir] as temporary directory for sort data, when used in
      conjunction with --max-mem=[value], instead of the host's operating system
      default temporary directory
```

Please try that option and see if it resolves this for you. If you still have problems, please follow up and I'll see if I can set up an Ubuntu 16 image here to test.

**Comment by mojaveazure** [comment]
That worked, thank you!

**Comment by alexpreynolds** [comment]
Nice! I'll close this up, but feel free to follow up if you run into problems.
