### ISSUE TITLE
convert2bed - could not allocate space

### ISSUE THREAD

**Issue by ehsueh** [bedops/bedops#170]
Hi Alex,

Thank you for your convert2bed tool from bedops.

I am using convert2bed (version 2.4.23) without the sorting option on my vcf file; however, I keep on getting errors on convert2bed not being able to allocate enough space:

> Error: Could not allocate space for VCF destination header line string

If I perform the same command on smaller subsets of the file, it works fine. Since I'm not asking the converted bed to be sorted, the conversion could really be processed line by line (much like awk) or in smaller batches without exceeding the buffer limit (right?), so I am wondering why there would be a memory allocation issue if the previous converted portions could be written to disk first and free up more mem for the next portion. Maybe I'm misunderstanding how it works :confused: 

Thank you for your time! :)

**Comment by alexpreynolds** [comment]
Thanks, I'll investigate and let you know what I find.

**Comment by alexpreynolds** [comment]
There is a memory leak for VCF conversion that I have patched in commit 7b76ad6

I'll try to put out a master release in the next day or two. You can also check out the `v2p4p24` branch and build from source, if you need a fixed version sooner.

**Comment by ehsueh** [comment]
:+1: Oh, I see. Thank you so much, Alex!
