### ISSUE TITLE
Please avoid csh

### ISSUE THREAD

**Issue by tillea** [bedops/bedops#172]
Hi,
I noticed that the Debian package policy checker was warning about the usage of csh inside bedops.  Please habe a look at the article [Csh Programming Considered Harmful](http://www.faqs.org/faqs/unix-faq/shell/csh-whynot/) to learn why using Csh in your scripts is not a good idea.  Feel free to contact me if you need assistance to migrate your scripts to POSIX shell (or bash if this is not feature complete for your application).
Kind regards, Andreas.

**Comment by sjneph** [comment]
Thanks for the note.  We are using tcsh, not csh.  I read through the information at the link provided, and it appears to be almost entirely subjective opinions about missing features and syntax complaints.  There is nothing inherently 'harmful' about tcsh, and it is almost certainly a Turing Complete language, though I haven't spent the time to prove that.   Either way, the couple of scripts that we provide to help with cluster management work well for our needs and do not require porting to a different programming language.  I will admit that bash has some features that would be handy in tcsh, and I hope to spend the time to get better with using bash in the near future.

**Comment by tillea** [comment]
I think that using tcsh brings an extra dependency to a default installation which has no better reason than personal shell preferences of some authors.  From a Debian maintainers perspective we have seen 10 or more packages only in the Debian Med team for bioinformatics packages that were affected by a release critical bug of tcsh.  To get rid of this dependency we as the Debian maintainers would consider a bash port and I just wanted to know whether you would accept such a write also in your upstream code which would increase our motivation to to this.  (no promises, thought)

-- 
http://fam-tille.de

**Comment by bedops** [comment]
Hi Andreas,

Thanks for the feedback. We'd love to have BEDOPS available to users via
Debian package managers. If you would like to try porting a utility script
to another language and post a pull request, we'll be happy to take a look.
We also look at making updates over time, as it makes sense, although our
development efforts are currently focused on other parts of the kit at the
moment.

Regards,
Alex
