### ISSUE TITLE
Potential bugs to investigate

### ISSUE THREAD

**Issue by alexpreynolds** [bedops/bedops#174]
Couple issues to investigate on return:

- [x] Possible `gtf2bed` issue: http://bedops.uwencode.org/forum/index.php?topic=136.0

- [x] Possible `unstarch` or C++ Starch API issue reported in email by Matt Maurano:

> I have some large starch files where performance is poor. I noticed that gzip starch files were about 6x faster than bzip2 starch files and only about 2x larger, so I tried switching.
> 
> This seems to have exposed some odd bug in the starch read code for bedops, where it complains about sort order when no problem seems to exist.
> 
> $ unstarch ~/scratch/hybridmice/dnase/prediction/fimo/hg19.allref.xfac.1e-4.starch | head -400000 | sort-bed --max-mem 32G -| starch --gzip - > /tmp/newvers.gzip.starch
> $ bedops -u /tmp/newvers.gzip.starch>/dev/null
> May use bedops --help for more help.
> 
> Error: in /tmp/newvers.gzip.starch
> Bed file not properly sorted by start coordinates.
> See row: 119250
> 
> There are no sorting problems I can see:
> $ unstarch /tmp/newvers.gzip.starch  | cat -n | head -119255| tail
> 119246  chr1    602339  602347  V_E2A_Q6        1.5e-05 +
> 119247  chr1    602339  602347  V_MYOGENIN_Q6   6.01e-05        -
> 119248  chr1    602342  602353  V_SMAD_Q6_01    4.31e-05        -
> 119249  chr1    602354  602366  V_ETS_Q4        3.94e-05        +
> 119250  chr1    602356  602369  V_CETS1P54_02   7.6e-05 -
> 119251  chr1    602357  602367  V_ESE1_Q3       4.37e-05        +
> 119252  chr1    602368  602381  V_MAZR_01       9.11e-05        -
> 119253  chr1    602369  602379  V_ZNF515_01     5.41e-05        -
> 119254  chr1    602375  602397  V_MEF2_04       5.04e-05        +
> 119255  chr1    602377  602393  V_FREAC3_01     5.11e-05        +
> 
> A few notes:
> * This happens in bedops 2.4.19 and 2.4.23.
> * It does not happen with --bzip2 starch archives
> * It does not happen if I pipe unstarch /tmp/newvers.gzip.starch | bedops
> * It does not happen if I keep fewer lines of the file (eg. head -300000).

[newvers.gzip.starch.zip](https://github.com/bedops/bedops/files/779190/newvers.gzip.starch.zip)

**Comment by alexpreynolds** [comment]
```
Thanks for the updates in bedops 2.4.25. I'm still having a few problems with the SLURM options in particular. First, update-sort-bed-migrate-candidates seems to call update-sort-bed-slurm with the option --output-new which is invalid.

This was hard to debug because update-sort-bed-migrate-candidates doesn't report the command or output of update-sort-bed-slurm (see attachment for rough version that does).

Also, I had trouble using my sandbox version of 2.4.25 since specifying paths to each utility manually is cumbersome (and there is no good error message if an invalid path is specified). How about just setting --bedops-path since most people will have everything in the same folder? Update-sort-bed-migrate-candidates could then also look for update-sort-bed-slurm in that location too (right now it needs to be in path).
```

**Comment by alexpreynolds** [comment]
Could not reproduce the `gtf2bed` issue (cf. https://dl.dropboxusercontent.com/u/31495717/genes.gtf.bed.bz2). Checking with the individual who reported problems to find how binaries were installed.

**Comment by alexpreynolds** [comment]
Reproduced `gtf2bed` issue on another host and fixed in commit 204ec4661c606ff6b284c20a9e7edd41fafdb0a5

**Comment by alexpreynolds** [comment]
On an Ubuntu 14 (64-bit) virtual machine, I wasn't able to reproduce the issue with v2.4.23, v2.4.24, or v2.4.26 binaries:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

$ ./bin/bedops -u /tmp/newvers.gzip.starch > /dev/null
$ echo $?
0
```

I tried a CentOS 7 host in our lab, and was not able to reproduce the issue, e.g.: 

```
$ cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core) 

$ module add bedops/2.4.23
$ bedops -u newvers.gzip.starch > /dev/null
$ echo $?
0
```

I could not reproduce the reported starch gzip issue with a recent OS X:

```
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32

$ ./bin/bedops -u /tmp/newvers.gzip.starch > /dev/null
$ echo $?
0
```

This is the archive I'm working with:

```
$ ./bin/unstarch --list-json /tmp/newvers.gzip.starch
{
  "archive": {
    "type": "starch",
    "customUCSCHeaders": false,
    "creationTimestamp": "2017-02-15T23:10:27-0500",
    "version": {
      "major": 2,
      "minor": 2,
      "revision": 0
    },
    "compressionFormat": 1
  },
  "streams": [
    {
      "chromosome": "chr1",
      "filename": "chr1.pid85108.isglcdctap001",
      "size": "3502433",
      "uncompressedLineCount": 400000,
      "nonUniqueBaseCount": 5271441,
      "uniqueBaseCount": 843737,
      "duplicateElementExists": true,
      "nestedElementExists": true,
      "signature": "KQdDdM5lE1miwNVSgdmzGIRRnx8=",
      "uncompressedLineMaxStringLength": 55
    }
  ]
}
```

**Comment by alexpreynolds** [comment]
Adding `--ec` to `bedops -u` triggers the reported error.

**Comment by zebasilio** [comment]
@alexpreynolds 

**About the gtf2bed issue**: somehow  I can't find your reply to me on the forum (26.2.1017) so I am answering your question here. This is how downloaded and installed the binary:
#! /bin/bash

#download x86-64 (64-bit) binaries for linux
cd ~/tools && wget "https://github.com/bedops/bedops/releases/download/v2.4.25/bedops_linux_x86_64-v2.4.25.tar.bz2" && 
#extract
tar jxvf bedops_linux_x86_64-v2.4.25.tar.bz2 &&
# copy to a folder in PATH
cp bin/* ~/bin

**Comment by alexpreynolds** [comment]
@zebasilio Thanks for getting back to me. I patched `gtf2bed` to address the bug you reported in commit 204ec46

Patched gzip-starch extraction issue in commit f4eb1ea

**Comment by alexpreynolds** [comment]
Yes, this is your GTF file converted to BED.

**Comment by alexpreynolds** [comment]
A bug with `starch-diff`:

```
$ starch-diff --chr chr1 /home/sjn/Github/BEDOPS/bedops/.foo.starch /home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch
Compressed genomic streams in input files are identical for chromosome [chr1]
```

Repeatable for other chrs.

**Comment by alexpreynolds** [comment]
`starch-diff` and `starchcat` patches applied in commit e677673 to help resolve comparison and archive upgrade problems.

**Comment by alexpreynolds** [comment]
Sample run with fixed `starch-diff`:

```
[areynolds@sched0 bedops]$ ./bin/starch-diff --chr chr1 /home/sjn/Github/BEDOPS/bedops/.foo.starch /home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch
WARNING: Signatures do not match for chromosome [chr1] between archives 
```

And on the full chromosome set:

```
[/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
[areynolds@sched0 bedops]$ ./bin/starch-diff /home/sjn/Github/BEDOPS/bedops/.foo.starch /home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch
WARNING: Signatures do not match for chromosome [chr1] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
WARNING: Signatures do not match for chromosome [chr10] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
WARNING: Signatures do not match for chromosome [chr11] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
WARNING: Signatures do not match for chromosome [chr12] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
WARNING: Signatures do not match for chromosome [chr13] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
WARNING: Signatures do not match for chromosome [chr14] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
WARNING: Signatures do not match for chromosome [chr15] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
WARNING: Signatures do not match for chromosome [chr16] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
WARNING: Signatures do not match for chromosome [chr17] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
WARNING: Signatures do not match for chromosome [chr18] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
WARNING: Signatures do not match for chromosome [chr19] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
WARNING: Signatures do not match for chromosome [chr2] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
WARNING: Signatures do not match for chromosome [chr20] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
WARNING: Signatures do not match for chromosome [chr21] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
WARNING: Signatures do not match for chromosome [chr22] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
WARNING: Signatures do not match for chromosome [chr3] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
WARNING: Signatures do not match for chromosome [chr4] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
WARNING: Signatures do not match for chromosome [chr5] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
WARNING: Signatures do not match for chromosome [chr6] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
WARNING: Signatures do not match for chromosome [chr7] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
WARNING: Signatures do not match for chromosome [chr8] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
WARNING: Signatures do not match for chromosome [chr9] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
WARNING: Signatures do not match for chromosome [chrX] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
WARNING: Signatures do not match for chromosome [chrY] between archives [/home/sjn/Github/BEDOPS/bedops/.foo.starch] and [/home/sjn/proj/encode3/vierstra/get.fp-motifs/results/.all.fp.regions.starch]
```

**Comment by alexpreynolds** [comment]
Closed remaining issues with sort-bed scripts via commits 715efd8 and c97eeeb

**Comment by qingyuemanwu** [comment]
Hello, thank you for your reply on Biostar, so I'm using bedextract on a large bedgraph file (query) in comparison to a target bed file, but realizing that it could only recognize chrX,Y,M, not chr1 to 22. (I also tried `bedextract chr1 file.bedgraph` and there is no return. But if I do` bedextract chrX file.bedgraph`, it will return all the chrX lines)

Any ideas about what is the problem? I have attached part of the bedgraph file here in txt format in case you need it.



[chr1.txt](https://github.com/bedops/bedops/files/1388587/chr1.txt)

**Comment by sjneph** [comment]
Thanks for using BEDOPS.  The `bedextact` utility has 2 requirements.  The first is required by virtually all of our tools - your bedgraph file must be sorted using our `sort-bed` program (which includes a `--max-mem` option).  It is a very fast tool.  The second requirement is that there are no fully-nested components in your query file, though there is a way around even this.  I'll share a link below that illustrates what "fully-nested" means for our tools better. In words, fully-nested means that you have two elements in a file where the first element has a start coordinate that is smaller than the second element's start coordinate, and it has an end coordinate that is bigger than the second element's end coordinate.  I'll also share a link on how to get around fully-nested elements if it's needed.

What version of `bedextract` are you using, btw?

Fully-nested elements illustrated:
https://bedops.readthedocs.io/en/latest/content/reference/set-operations/bedextract.html#what-are-nested-elements

How to use bedextract with fully-nested elements (it's very fast).  Start at the blue 'Note' that reads, "With some extra work...":
https://bedops.readthedocs.io/en/latest/content/reference/set-operations/bedextract.html#retrieving-elements-from-a-specific-chromosome

**Comment by alexpreynolds** [comment]
I ran `bedextract` on your attachment and I got back the same number of lines and the same bytes:

```
$ bedextract chr1 /Users/areynolds/Downloads/chr1.txt | wc -l
  100000
$ wc -l /Users/areynolds/Downloads/chr1.txt
  100000 /Users/areynolds/Downloads/chr1.txt
```

Here's a `diff` comparing the output of `bedextract` and `cat`:

```
$ diff -s <(bedextract chr1 /Users/areynolds/Downloads/chr1.txt) <(cat /Users/areynolds/Downloads/chr1.txt)
Files /dev/fd/63 and /dev/fd/62 are identical
```

My advice would be like Shane's: use `sort-bed` to make sure your bedgraph file is sorted. Also make sure that your file does not contain fully-nested elements. 

I posted an `awk` utility script on this page that takes in a sorted BED file and prints any nested elements:

http://bedops.readthedocs.io/en/latest/content/reference/set-operations/nested-elements.html

You could run your (sorted) bedgraph file through this `awk` script and pipe the result to `wc -l` to count the number of lines. 

If that count is greater than zero, then you cannot use `bedextract` directly, and you would either use the approach that Shane details in the second link in his answer, or use `bedops -e 1`.

If you still have problems, please try to provide:

* The version of BEDOPS you are using 
• The full inputs and commands you are using
• Some information about your environment (OS, version, etc.)

Also, if you still run into problems, please open a new ticket, if you can. If there really is a bug, it helps us if we can track and discuss it separately from older issues.

**Comment by qingyuemanwu** [comment]
Thank you for your prompt reply Alex and Shane. I did not sort my bedgraph
because I thought it was sorted in bedtools, but apparently another sort
with bedops is needed, and it seems to work after that. I appreciate your
time and attention to this matter.

Best,

Helen

**Comment by alexpreynolds** [comment]
Glad to hear it is working! Thanks for using BEDOPS and let us know if you run into any further problems.

**Comment by htpmod** [comment]
Hi, it seems that starch has some problem when the bed file containing "." in the chromosome column: 
GL002604.1      0       8818317
GL002605.1      0       7339604
GL002606.1      0       7120037

all the characters after "." were removed by starch. Is this a bug? Or I have to prepare a bed file without "." in the chromosome column? 
Thank you!

**Comment by alexpreynolds** [comment]
Thanks, I'll investigate.
