### ISSUE TITLE
sam2bed failing (because of long CIGAR?)

### ISSUE THREAD

**Issue by mutundis** [bedops/bedops#179]
I am trying to use sam2bed (version: 2.4.12) to convert SAM format output produced by blastn and while this usually works I find that occasionally a conversion fails, apparently because the CIGAR string is too long (because of lots of little indels in the alignment).

An example sam input:

@HD	VN:1.2	SO:coordinate	GO:reference
@SQ	SN:scaf00003	LN:38256937
@PG	ID:0	VN:2.5.0+	CL:blastn -query_loc 763487-764054 -db mhdb -seqidlist ok.ids -outfmt 17 -parse_deflines 	PN:blastn
query_23453	16	scaf00003	763488	255	76H29M1D29M1D16M1I8M1I1M1I8M1D24M1D24M1I12M1I70M1D6M1D13M2D42M1D26M1I4M1I23M1I41M1D4M1I2M1I51M1D61M1D8M1D33M1D16M1126H	*	0	0	*	*	AS:i:467	EV:f:0	NM:i:24	PI:f:98.55	BS:f:863.506

and the error when attempting to convert it:

cat foo2.sam | sam2bed
scaf00003	763487	765264	query_23453	255	-	16	76H29M1D29M1D16M1I8M1I1M1I8M1D24M1D24M1I12M1I70M1D6M1D13M2D42M1D26M1I4M1I23M1I41M1D4M1I2M1I51M1D61M1D8M1D33M1D16M1126H	*	0	0	*	*	AS:i:467	EV:f:0	NM:i:24	PI:f:98.55	BS:f:863.506
/usr/local/bin/sam2bed: line 148: 52598 Abort trap: 6           ${cmd} ${options} - 0<&0

Thanks

**Comment by alexpreynolds** [comment]
I suggest upgrading to version 2.4.26 of the suite. There have been a number of improvements to the conversion kit since version 2.4.12. Please try the new version and follow up here if you are still having difficulties.

Regards,
Alex

**Comment by mutundis** [comment]
Yes that solved my problem - thank you!
