### ISSUE TITLE
convert2bed output with repeatmasker as input does not result in typical bed or gff?

### ISSUE THREAD

**Issue by cmdcolin** [bedops/bedops#184]
Hi there, I was trying to use convert2bed to get repeatmasker output files into bed format, but ran into a small problem

```
$ convert2bed -i rmsk < input.rm.out | head -n 100
...
LINE/L1 (0)     6155    5105    80
NC_000001.11    74897   76697   L1PA2   14711   +       2.100   0.000   0.000   (248879725)     LINE/L1 3311    5110    (1036)  80
NC_000001.11    76692   76892   L1MC5a  1229    +       25.000  8.800   4.000   (248879530)     LINE/L1 5515    5738    (2292)  81      *
NC_000001.11    76892   77201   AluSz   2295    +       12.900  0.000   0.000   (248879221)     SINE/Alu        1       309     (3)     82
NC_000001.11    77201   77707   L1MC5a  1229    +       25.200  8.900   4.000   (248878715)     LINE/L1 5739    6272    (1758)  81
NC_000001.11    77716   77861   L1MC5a  291     +       27.600  6.900   2.600   (248878561)     LINE/L1 7164    7314    (716)   81
NC_000001.11    77940   78235   L1MC5a  465     +       33.200  2.400   0.000   (248878187)     LINE/L1 7436    7737    (293)   81
```

This seems like it could be possibly bed format, but at least one thing that happens here is that sometimes the lines from this have unequal number of columns (see the extra asterisk on some lines above) and that confuses some downstream tools like `bedtools maskfasta`

I also tried using convert2bed -i rmsk -o gff but the output was the same, not really gff format

```
$ convert2bed --version
convert2bed
  version:  2.4.26
  author:   Alex Reynolds
```

I did get a workable solution just slicing the first three columns of the bed for maskfasta

**Comment by alexpreynolds** [comment]
`convert2bed` aims to be non-lossy and so will convert everything it can convert. Depending on the input, this can result in output with variable numbers of columns, which seems to trip up other `bedtools` scripts as well, like `sortBed` etc. I can't do much to fix `bedtools`, but if you need to guarantee truncated output and don't mind throwing away data, it seems fine to use `cut -fA-B` to get columns from index A to B.

`convert2bed` writes either BED or Starch as output. It will not write GFF or other genomic formats. Please take a look at `convert2bed --help` or `rmsk2bed --help` for more specifics, or the online documentation at: http://bedops.readthedocs.io/en/latest/content/reference/file-management/conversion.html

**Comment by cmdcolin** [comment]
Sounds good! I guess for some reason I thought I saw that gff was allowed in the -o field of convert2bed, but I suppose not

+1 for the rmsk2bed command! the repeatmasker output is so weird by itself, very glad this tool exists...

**Comment by alexpreynolds** [comment]
Thanks for the feedback! Please let us know if you run into any other problems.
