### ISSUE TITLE
BEDOPS.2.4.27.pkg contains broken symbolic links

### ISSUE THREAD

**Issue by rsharris** [bedops/bedops#188]
I'm new to BEDOPS.  I downloaded and installed the pre-built mac version, 2.4.27.  I see many files it copied into /usr/local/bin. convert2bed is defined as a symbolic link to ./convert2bed-typical, but there is not convert2bed-typical in /usr/local/bin.

I also noticed that when I unzipped the zip file, in unzipped to a folder and the actual .pkg file was buried several layers down the hierarchy.

I eventually found 2.4.26 which seems to have convert2bed as a CAFEBABE binary.  No symbolic links.  The zip file unzipped to a pkg, not to a folder.

**Comment by alexpreynolds** [comment]
Thanks, I'll investigate.

**Comment by alexpreynolds** [comment]
Thanks for the bug report.

I replaced the pkg.zip file in the 2.4.27 release with one that extracts, by default, to the local or current working folder.

When I installed this package on a Mac OS X 10.12.6 host, I get binaries and symbolic links in the correct location:

```
$ which bedops
/usr/local/bin/bedops
$ ls -al `which bedops`
lrwxr-xr-x  1 root  wheel  16 Jul 26 12:28 /usr/local/bin/bedops -> ./bedops-typical
```

When I run `--version`, the binary shows the correct version information:

```
$ bedops --version
bedops
  citation: http://bioinformatics.oxfordjournals.org/content/28/14/1919.abstract
  version:  2.4.27 (typical)
  authors:  Shane Neph & Scott Kuehn
```

Symbolic links for the primary binaries and scripts are expected. They point to either of their `-typical` or `-megarow` variants. You can use the `switch-BEDOPS-binary-type` script to switch the variant:

```
$ switch-BEDOPS-binary-type --help
Switch the BEDOPS binary build from typical to megarow, or vice versa
Usage: switch-BEDOPS-binary-type [ --help ] [ --typical | --megarow ]
```

The `-typical` binaries are the default and cover most usage cases. Please see the release history for 2.4.27 for more information about `-megarow` and why one might use it: http://bedops.readthedocs.io/en/latest/content/revision-history.html#v2-4-27

Please try downloading and re-running the updated installer package. If you're still having difficulties, then you might run the same commands that I list above (`which`, `ls -al`, etc.) and paste the results in this thread, along with your OS version, and I can follow up from there.

**Comment by rsharris** [comment]
OK ... it may be a couple days before I try it.  I'm up against a deadline and my workaround is to use the earlier version.

**Comment by alexpreynolds** [comment]
No problem, thanks for the report. Hopefully the updated zip file works for you.
