### ISSUE TITLE
closest-features to report upsteam/downstream features only

### ISSUE THREAD

**Issue by isthisthat** [bedops/bedops#189]
This is a feature request for closest-features. Would it be possible to add a switch to report upsteam or downstream features only? (when features overlap, the overlap should be reported as before). I assume strandedness is already supported? Thank you.

**Comment by sjneph** [comment]
Thanks for the feature request.  Originally, our tools considered strand information, but that was removed when it interfered somewhat with supporting other features.  It is a little annoying but easy to get around this limitation by partitioning your input files into separate + and - strand files.  They can be left this way, or results can be combined later with bedops --union.

I'll assume that strand info is in the 6th column below:

awk '$6 == "+"' myGeneFile.bed \
  | closest-features --no-ref - myFeatures.bed \
  | awk -F"|" '($1 != "NA") { print $1 }' \
  | sort-bed - \
> plus-results.bed

awk '$6 == "-"' myGeneFile.bed \
  | closest-features --no-ref - myFeatures.bed \
  | awk -F"|" '($2 != "NA") { print $2 }' \
  | sort-bed - \
> minus-results.bed

**Comment by sjneph** [comment]
Edited some of that code to get rid of my markdown mistakes.

**Comment by alexpreynolds** [comment]
To report upstream or downstream features only, you could pipe to `awk`:

```
$ closest-features genes.bed features.bed |  awk -F'|' '{print $1"|"$2}' > upstream.bed
$ closest-features genes.bed features.bed |  awk -F'|' '{print $1"|"$3}' > downstream.bed
```

If `--dist` is used, the `$3` value in the downstream `awk` statement would be changed to `$4`.

**Comment by alexpreynolds** [comment]
Shane's answer is better, on reflection.

**Comment by isthisthat** [comment]
Thank you both for your replies. This works for me except in case of an overlap, when I always want to keep the overlap. I could use the `--dist` argument and an if statement I guess. Is there some logic to determine whether the overlap appears on the left or the right?

**Comment by alexpreynolds** [comment]
Since `--dist` returns a zero distance value, I think you might need to  split the feature results on their delimiters, further split to get start and stop coordinates, and compare them against the start and midpoint coordinates of the gene. If a feature's coordinates overlap that half, it's a "left-half" overlap. Otherwise, it is a "right-half" overlap. This test could be put into an `awk` script, which could print out a "left" or "right" annotation along with the gene and feature hit.

**Comment by sjneph** [comment]
You could unionize those elements that overlap with those passing through your stranded filter (adding bedops -u to previous code):

awk '$6 == "+"' myGeneFile.bed \\
| bedops -u - \<(bedops -e 1 myGeneFile.bed myFeatures.bed) \\
| closest-features --no-ref - myFeatures.bed \\
| awk -F"|" '($1 != "NA") { print $1 }' \\
| sort-bed - \\
\> plus-results.bed

This gives the actual bases of overlap between the files, and the gene name if located in col4:
bedops -i myGeneFile.bed myFeatures.bed \\
 | bedmap --echo --echo-map-id --delim "\t" - myGeneFile.bed

Again, if the gene name is in col4, then something like this will tell you left or right of overlapping elements:
awk '{ print $1, $2, $2+1, $4"-leftedge"; print $1, $3-1, $3, $4"-rightedge"; }' myGeneFile.bed \\
| sort-bed - \\
| bedops -e - myFeatures.bed

These ideas can all be combined and/or tweaked.  Let us know if you have other questions.

**Comment by sjneph** [comment]
It seems this issue has been resolved.
