### ISSUE TITLE
What is the equivalent command of genomeCoverageBed in bedops?

### ISSUE THREAD

**Issue by gk7279** [bedops/bedops#190]
Hi bedops team,

I have a bed file and chrom sizes file and would like to get the depth at each position from this bed file.

Currently using genomecoveragebed for this purpose. But it takes two days without any support for parallel processing. Is there a module/program in bedops that does what genomecoveragebed does?

Kindly advice.

Cheers

**Comment by alexpreynolds** [comment]
Adjusting the smoothing and step parameters in the usage example here may help replicate a coverage analysis:

http://bedops.readthedocs.io/en/latest/content/usage-examples/smoothing-tags.html

Effectively, you may adjust the script parameters to walk over the genome with a one-base window and one-base step — or adjust these, depending on the resolution you need.

To parallelize, you could loop over the list of chromosomes in your input BED file by running `bedextract --list-chr in.bed` and storing that result in an array, list, vector — whatever your script language uses to store the equivalent of an array.

For each chromosome, you could launch a per-chromosome job on your computational cluster. Adjust the input to `awk` to build per-base windows over the specified chromosome. Add the chromosome name to the arguments in the `bedmap` call to focus work on just that chromosome. You could then collate the results at the end with `bedops -u`.

The graphical overview for generating Starch archives via a cluster can offer a more visual explanation of how to parallelize the work:

http://bedops.readthedocs.io/en/latest/content/usage-examples/starchcluster.html#stitching-together-compressed-sets

**Comment by alexpreynolds** [comment]
Sorry, I accidently closed this. I'll re-open, in case Shane or others want to comment.

**Comment by sjneph** [comment]
What option in particular are you interested in using?
`bedops -p your-input | bedmap --echo --count --delim "\t" - your-input`

will partition your input file(s) in the way that they do (at least one of their options) and count how many distinct regions overlaps each.  Another route might be the --bases or --bases-uniq option that comes with bedmap.  If you can show you current full command, we can match things up.

**Comment by gk7279** [comment]
Hi @sjneph -

Thank you for your response. Here is my current bedtools command

`genomeCoverageBed -d -i input.bed -g chrsizes.txt > cov.out`

Appreciate your prompt response.

**Comment by sjneph** [comment]
OK, thanks.  The -d option assumes 1 based coordinates, which is fine so long as *all* of your input files are 1-based with BEDOPS - then the output will be too.  Your chrsizes.txt will need to be 3 column BED, and sorted with our sort-bed program (as will your input.bed).  If chrsizes.txt is 2 column chrom/size, then just add a 1 in the second column and push the size to the 3rd column (then run through sort-bed - this is important).

I may mess up some of my markdown syntax below.  If the email looks bad, check at the github page, and I'll make sure it's okay here.

You will likely find that the enumerating all of the zeroes and breaking them down into 1 bp segments takes the longest.  In bash, I might do something like this:

```
# sorting is fundamental in BEDOPS; this will be very quick
sort-bed input.bed > input.sort.bed
awk '{ print $1, 1, $2 }' chrsizes.txt | sort-bed - > chrsizes.bed

# deal with regions with 0s in separate process (can modify if input.sort.bed has 0 entries)
bedops --chop input.sort.bed \
| bedmap --echo --count --delim "\t" - input.sort.bed \
| bedops -u - <(bedops -d chrsizes.bed input.sort.bed | bedops --chop - | awk '{print $1"\t"$2"\t"$3"\t0"}') \
> answer.bed
```

That certainly isn't as pretty as a 1 liner, but you'll have 6 processes running in parallel and things will be much faster.  Breaking things down by chromosome per Alex's suggestion is very helpful too.  Because you sorted your 2 input files, your output in answer.bed will be too - so you never need to sort that to use it with BEDOPS.

**Comment by sjneph** [comment]
Also, you should add --faster to the bedmap statement (which I will edit to show this now).

**Comment by gk7279** [comment]
Thanks @sjneph.

I get an error with union command.

`May use bedops --help for more help.

Error: Bad Input
Unknown operation: --union`

**Comment by sjneph** [comment]
Ah, sorry.  It is suppose to be -u or --everything.  I rarely use the longer words.  Please try again with the update.

**Comment by gk7279** [comment]
Thanks. It is very fast. Working great. However, I have a quick question.

Bedtools output is

```
chr1 1 0
chr1 2 0
...
```

Whereas bedops is

```
chr1 1 2 0
chr1 2 3 0
....
```

So can I just pick the 1st, 2nd and 4th columns for my downstream?

Bedops is really fast compared to bedtools which takes 2days to finish. Bedops takes little time between 2-4hrs for a full genome.

**Comment by sjneph** [comment]
If your downstream tools expect that, then yes.  It's just not in BED format anymore so you wouldn't use BEDOPS downstream after doing that.  Thanks for the feedback on performance.  It sounds like we can close out this issue.  Feel free to re-open or comment further as needed.

**Comment by gk7279** [comment]
Thanks. It is done in less than 24mins. Not 2-4hours. My mind was a bit confused. Closed.
