### ISSUE TITLE
Converting WIG to BED file

### ISSUE THREAD

**Issue by claudiadast** [bedops/bedops#192]
Hello, I've download the UCSC WIG files for PhyloP scores, which are in the format .wigFix.gz, and I tried using BEDOPS to convert them to .bed format, via convert2bed. However it doesn't appear to be working. The command I used was:

`convert2bed --input=wig --output= bed < chr10.phyloP46way.wigFix.gz > chr10.phyloP46way.bed` 

It gave an error: "Invalid WIG line 1".

**Comment by alexpreynolds** [comment]
Please try:

```
$ gunzip -c chr10.phyloP46way.wigFix.gz | convert2bed --input=wig --output=bed - > chr10.phyloP46way.bed
```

Or use the wrapper:

```
$ gunzip -c chr10.phyloP46way.wigFix.gz | wig2bed - > chr10.phyloP46way.bed
```

The WIG files are compressed gzip files, and you'll need to pipe in uncompressed WIG data. The above should get you going, unless there are other issues.

**Comment by claudiadast** [comment]
Thanks, that seems to be working!

**Comment by alexpreynolds** [comment]
Cool, I'll just close this up.
