### ISSUE TITLE
comapre two bam files based on read ID

### ISSUE THREAD

**Issue by gk7279** [bedops/bedops#201]
Hi Bedops Team-

Good Morning.

Can bedops compare two bam files based on **read id** and print out three files saying uniquetofirst, uniquetosecond and common?

Thanks

**Comment by alexpreynolds** [comment]
BEDOPS tools generally do set operations on genomic intervals, not metadata. 

You might integrate set operations with `grep` on IDs:

```
$ bam2bed < A.bam > A.bed
$ bam2bed < B.bam > B.bed
$ bedops --everything A.bed B.bed > AB.bed
$ cut -f4 A.bed | awk '{n=split($1,a,":"); print a[1];}' > A_IDs.txt
$ cut -f4 B.bed | awk '{n=split($1,a,":"); print a[1];}' > B_IDs.txt
$ grep -Ev -f B_IDs.txt AB.bed > A_unique.bed
$ grep -Ev -f A_IDs.txt AB.bed > B_unique.bed
$ bedops --everything A_unique.bed B_unique.bed > AB_unique.bed
$ bedops --not-element-of 100% AB.bed AB_unique.bed > AB_common.bed
```
![img_7444](https://user-images.githubusercontent.com/33584/33041135-21669cf0-cdf2-11e7-82f7-4709020b0532.jpg)

You'd want to test this on smaller files, if you decide to go this route.
