### ISSUE TITLE
Add support for merging GZIP (or BGZIP) BED files

### ISSUE THREAD

**Issue by fgvieira** [bedops/bedops#214]
`bedops` support `gzip/bzip` files on starch but not when merging BED files.
Would it be possible to add this feature?
thanks,

**Comment by sjneph** [comment]
Thanks for the request.  You can get that effect using process substitutions in bash.
Something along these lines will do what you want:
```
bedops -m <(zcat file1.bed.gz) <(zcat file2.bed.gz) <(zcat file3.bed.gz) > answer.bed
```
