### ISSUE TITLE
`POS + length(CIGAR) - 1` should be `POS + length(SEQ) - 1`

### ISSUE THREAD

**Issue by dongzhuoer** [bedops/bedops#215]
![image](https://user-images.githubusercontent.com/15871952/50225909-c38d0c00-03dc-11e9-8686-c3e0a987c2d0.png)

**Comment by dongzhuoer** [comment]
Both documentation website and program help message need to be updated.

**Comment by alexpreynolds** [comment]
I will keep this open to make sure I review this before the next version is released.

**Comment by alexpreynolds** [comment]
Patched in commit 02578a85
