### ISSUE TITLE
Merge only overlapping regions

### ISSUE THREAD

**Issue by nandankita** [bedops/bedops#216]
I have two files which I want to merge but only when it's overlapping even with 1 base pair but not the adjoining element regions. Is there a way to do this in bedops --merge ?

**Comment by alexpreynolds** [comment]
If you only want to merge those elements which have, at minimum, one base pair of overlap with each other within a sorted BED file `in.bed`, here is one way to do that:

```
$ bedmap --count --echo --bp-ovr 1 --skip-unmapped --delim '\t' in.bed | awk '($1>1)' | cut -f2- | bedops --merge - > answer.bed
```

The file `answer.bed` will contain the merge of all elements from `in.bed` which overlap one or more bases. It's a bit indirect; there are other ways, I'm sure.

The above pipeline is for one file. More generally, for two or more files, you could first take the union of the elements in all N files, and pipe that set to `bedmap`:

```
$ bedops --everything A.bed B.bed ... N.bed | bedmap --count --echo --bp-ovr 1 --skip-unmapped --delim '\t' - | awk '($1>1)' | cut -f2- | bedops --merge - > answer.bed
```

**Comment by nandankita** [comment]
Perfect! Thank you so much! Just to mention that the listed solutions here give me different results for the same two bed files and the second solution works according to my requirements.

**Comment by alexpreynolds** [comment]
I think I misunderstood your question. For clarification, here is a scenario I interpreted from your question:

```
$ cat in.bed
chr1    100     200
chr1    199     300
chr1    300     400
```

The first two elements have one base of overlap. The third element does not overlap with the first two.

My answer merges only those elements which meet the overlap criterion, and does not apply a merge operation on any elements that do not:

```
$ bedmap --count --echo --bp-ovr 1 --delim '\t' in.bed | awk '($1>1)' | cut -f2- | bedops --merge -
chr1	100	300
```

Shane's answer is different, as it merges all elements that overlap, while also preserving adjacent elements:

```
$ bedops --merge --range 1:0 in.bed | bedops -u --range -1:0 -
chr1	100	300
chr1	300	400
```

I'll close this up, but please follow up if you have any more questions.

**Comment by krukanna** [comment]
Hi,
I've got similiar issue, but I would like to find regions from bed, which overlap fraction is 0.9 (`bedmap --echo --fraction-both 0.9 --echo-map-id --count --echo-map-range --multidelim ', ' --delim '\t' `) and merge this regions. How should I combine this commands?
At the end I would like to get rows with merged ranges and their unique ID values in new column (echo-map-id).
Thanks in advance.
Best, 
Anna

**Comment by krukanna** [comment]
In addition to the previous message.
I would like to avoid situation, where one sample is counted several times - so the solution for me is to select best match for every sample or the match where the number of rows is minimized and at the same time each sample has a mapping in the result file.

Output from `bedmap --echo --echo-map-range --echo-map-id-uniq --count --fraction-both 0.9 --delim '\t' --multidelim ', '`
```
chr2	97083737	97113938	sample1	0	+	97083737	97113938	255,128,128	chr2	97083737	97113938	sample1	1
chr2	97083737	97151958	sample2	0	+	97083737	97151958	255,128,128	chr2	97083737	97158671	sample2, sample4, sample3	3
chr2	97083737	97154757	sample3	0	+	97083737	97154757	255,128,128	chr2	97083737	97158671	sample2, sample4, sample3	3
chr2	97083737	97158671	sample4	0	+	97083737	97158671	255,128,128	chr2	97083737	97163348	sample2, sample4, sample3, sample5	4
chr2	97083737	97163348	sample5	0	+	97083737	97163348	255,128,128	chr2	97083737	97163348	sample4, sample5	2
```
Desired output could look like: (or with more rows if the highest fraction-both scores are taken into account)
```
chr2	97083737	97113938	sample1	0	+	97083737	97113938	255,128,128	chr2	97083737	97113938	sample1	1
chr2	97083737	97158671	sample4	0	+	97083737	97158671	255,128,128	chr2	97083737	97163348	sample2, sample4, sample3, sample5	4
```
Best,
Anna
