### ISSUE TITLE
Multiple crashes when using convert2bed

### ISSUE THREAD

**Issue by HongxuChen** [bedops/bedops#217]
When feeding convert2bed with some crafted files, it may abort or cause segfault. Details can be seen from gdb.

```
Aborted                 ./convert2bed -i gvf -o bed --do-not-sort < c00.gvf > /dev/null
Aborted                 ./convert2bed -i gvf -o bed --do-not-sort < c01.gvf > /dev/null
Aborted                 ./convert2bed -i gff -o bed --do-not-sort < c00.gff > /dev/null
Aborted                 ./convert2bed -i gtf -o bed --do-not-sort < c00.gtf > /dev/null
Segmentation fault      ./convert2bed -i rmsk -o bed --do-not-sort < c00.out > /dev/null
Aborted                 ./convert2bed -i wig -o bed --do-not-sort < c00.wig > /dev/null
Aborted                 ./convert2bed -i wig -o bed --do-not-sort < c01.wig > /dev/null
```

Proof-of-Crash files are attached.
[bedops-report.zip](https://github.com/bedops/bedops/files/2844094/bedops-report.zip)

**Comment by alexpreynolds** [comment]
Thanks, I'll look into what I can do to test for malformed input for a subsequent version. I do make some assumptions that the input follows specification. 

I'll keep this open for now — depending on what my bandwidth allows, there might be fixes in the next version.

**Comment by alexpreynolds** [comment]
Patches in commit 727d9812 for GVF, GFF, GTF, Wiggle and RepeatMasker conversion on malformed inputs.
