### ISSUE TITLE
bedmap --header produces no output

### ISSUE THREAD

**Issue by vulpescu** [bedops/bedops#220]
I am finding that I need to strip all headers from my starch files before piping them into bedmap in order to get the proper output, even when using the `--header` tag. 

Download toy example [here](https://github.com/bedops/bedops/files/2938555/bedops_header_test.sh.zip) or view output below:

`bedops --version`
> bedops
  citation: http://bioinformatics.oxfordjournals.org/content/28/14/1919.abstract
            https://doi.org/10.1093/bioinformatics/bts277
  version:  2.4.35 (typical)
  authors:  Shane Neph & Scott Kuehn

**snp_file_header.hg19.starch contents:**
> #chrom	chromStart	chromEnd	rsid
chr1	1121013	1121014	rs3813204
chr1	1121340	1121341	rs4297230
chr1	1121793	1121794	rs11260549
chr1	1122023	1122024	rs4314833

**snp_file_noheader.hg19.starch contents:**
> chr1	1121013	1121014	rs3813204
chr1	1121340	1121341	rs4297230
chr1	1121793	1121794	rs11260549
chr1	1122023	1122024	rs4314833

**First run:**
`bedmap --header --echo --echo-map snp_file_header.hg19.starch snp_file_noheader.hg19.starch`

**Second run:**
`unstarch snp_file_header.hg19.starch | bedmap --header --echo --echo-map - snp_file_noheader.hg19.starch`

> chr1	1121013	1121014	rs3813204|chr1	1121013	1121014	rs3813204
chr1	1121340	1121341	rs4297230|chr1	1121340	1121341	rs4297230
chr1	1121793	1121794	rs11260549|chr1	1121793	1121794	rs11260549
chr1	1122023	1122024	rs4314833|chr1	1122023	1122024	rs4314833

**Comment by sjneph** [comment]
Thanks for the report - we will look into this soon.

**Comment by mattmaurano** [comment]
Hi Shane and Alex

I hope all is well! Andre just started in my lab and was able to take a look at this issue. Maybe when you get a chance you can take a look at his PR with his proposed fix?

The only thing that came to mind is that maybe his header handling should be conditional on the --header flag, though I'm a bit confused since the code suggests that bedmap --header is just an alias for --ec

**Comment by bedops** [comment]
Hi Matt,

Hope you are well. I have some other long overdue updates to push as well.
I'll try to look at this either today or tomorrow, esp. the portions of the
patch that involve the starch API.

Regards,
Alex

**Comment by bedops** [comment]
I apologize, but I'll have to push this back a few days for some lab work
that has come up. I will follow up on this as soon as I can.

-Alex

**Comment by alexpreynolds** [comment]
Fixed in https://github.com/bedops/bedops/releases/tag/v2.4.37
