### ISSUE TITLE
bedextract segmentation fault when operating on Agilent SureSelect v4+UTR regions file

### ISSUE THREAD

**Issue by khughitt** [bedops/bedops#222]
# Overview

When calling `bedextract` as part of a [variant calling pipeline](https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling), I am encountering a segfault.

core dump: [Download (110KiB)](https://drive.google.com/open?id=1orASxaW0OCMoB5BTs3atjQp5Fsr4lTmk)

**backtrace:**

```sh
bedextract chr19_gl000208_random /data/ref/human/agilent/sureselect_v4utr/S03723424_Regions.bed > called/chr19_gl000208
_random.regions.bed

Process 44641 (bedextract) of user 1000 dumped core.
                                               
                                               Stack trace of thread 44641:
                                               #0  0x00007fc002f38278 __vfscanf_internal (libc.so.6)
                                               #1  0x00007fc002f33538 fscanf (libc.so.6)
                                               #2  0x0000562b987bfe5c n/a (bedextract)
                                               #3  0x0000562b9878d090 n/a (bedextract)
                                               #4  0x00007fc002f03ce3 __libc_start_main (libc.so.6)
                                               #5  0x0000562b9878e80c n/a (bedextract)
```

The SureSelectV4+UTR regions bed file was downloaded from https://earray.chem.agilent.com/suredesign/index.htm.

# System info

- Arch Linux 5.1.2 (64-bit)
- Bedops 2.4.36
- glibc 2.29-1 (system)
- libstdc++.so.6.0.25 (conda installed)

bedops installed via conda environment:

```yaml
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bedops =2.4
```

**Comment by alexpreynolds** [comment]
> The SureSelectV4+UTR regions bed file was downloaded from https://earray.chem.agilent.com/suredesign/index.htm.

Would this file be available separately? I'd like to try to investigate this, but I don't have an account to access this product.

Failing that, I recommend compiling BEDOPS directly via instructions at: https://bedops.readthedocs.io/en/latest/content/installation.html#installation-via-source-code

Conda/bioconda can do some weird things with compilation that result in bad binaries, and I probably won't have time to debug that portion.

If this is no longer an issue, just let me know and I'll close this up.

**Comment by khughitt** [comment]
Hey! Apologies for not responding sooner. I'm not sure if the file is available anywhere else, unfortunately.

If I come across it though, or am able to recapitulate the problem using a different publically available file, I will follow up in the future. For now though, it's fine to leave this closed. Thanks!
