### ISSUE TITLE
bedops readthedocs index page image links seem to be broken

### ISSUE THREAD

**Issue by udincer** [bedops/bedops#224]
Images in the main bedops documentation page seem to be broken, the images within subpages are OK.

See:
https://bedops.readthedocs.io/en/latest/index.html

**Comment by alexpreynolds** [comment]
Thanks for the report!

There's a bug with readthedocs (RTD) that I filed an issue with them about (
https://github.com/rtfd/readthedocs.org/issues/5709).

The v2p4p36 branch docs work, but the master branch (which is a copy of the
v2p4p36 branch, effectively) does not.

I'm trying to find a workaround on my own, but the RTD logs contain no
error messages, so it's kind of a "black box" from my end of things.

**Comment by alexpreynolds** [comment]
Fixed in v2p4p37 branch and currently live.
