### ISSUE TITLE
Invalid WIG line when using wig2bed on wig obtained using bigWigToWig

### ISSUE THREAD

**Issue by blaiseli** [bedops/bedops#227]
I don't know whether this is an issue with USCS tools or bedops:

```
$ cat test.bedgraph
track type=bedGraph name=test
test    0       10      356.0
test    10      20      312.0
test    20      30      330.0
test    30      40      328.0
test    40      50      438.0
test    50      60      480.0
test    60      70      438.0
test    70      80      370.0
test    80      90      412.0
test    90      100     356.0
$ cat chrom_sizes.txt
test    100
$ bedGraphToBigWig test.bedgraph chrom_sizes.txt test.bw
$ bigWigToWig test.bw test.wig
$ wig2bed --zero-indexed < test.wig > test.bed
Error: Invalid WIG line 2
```

Or is my initial bedgraph not valid?

I'm using bedops version 2.4.36 and UCSC tools version v373.

**Comment by alexpreynolds** [comment]
I'm surprised, but it might be a bug with the UCSC tools:

```
$ bedGraphToBigWig test.bg chrom_sizes.txt test.bw
$ bigWigToWig test.bw test.wig
$ more test.wig
#bedGraph section test:0-100
test    0       10      356
test    10      20      312
test    20      30      330
test    30      40      328
test    40      50      438
test    50      60      480
test    60      70      438
test    70      80      370
test    80      90      412
test    90      100     356
```

That looks more like a bedGraph file embedded in a WIG (wiggle) file, and not a true wiggle-formatted file cf. examples at the bottom of: http://genome.ucsc.edu/goldenPath/help/wiggle.

You might send a message to the UCSC folks:

https://groups.google.com/a/soe.ucsc.edu/forum/#!forum/genome

I'm not sure what `wig2bed` could do to deal with this, other than to maybe look for a `#bedGraph` comment and rewrite what follows into five-column BED? I try to work off specification and this doesn't seem to follow it.

**Comment by alexpreynolds** [comment]
It looks it is documented at the bottom, here, kind of?

http://genome.ucsc.edu/goldenPath/help/bigWig.html#optional

It looks like `bigWigToWig` is trying to be helpful, but as this isn't a WIG file `wig2bed` isn't useful here. 

Thanks for the post. I'm going to close this up, but feel free to follow up if you run into any other issues.
