### ISSUE TITLE
sam2bed output fault

### ISSUE THREAD

**Issue by arnavgupta06754** [bedops/bedops#231]
Hello,
I am able to run sam2bed (I use linux on a computing cluster server) in my command line. However, any time I try to enter the output into a destination file submitted through slurm, my output file returns empty. Please advise.
My command (in script):
sam2bed -i sam -o bed < ${INDIR}/Sm25_ATACseq-Ctrl1_R1.trimmed.sam > ${OUTDIR}/Sm25_ATACseq-Ctrl1_R1.reads.bed

**Comment by alexpreynolds** [comment]
The `sam2bed` portion is a wrapper around `convert2bed`. You don't need `-i sam` as this is implicit in use of `sam2bed`. 

In any case, can you use Slurm's output and error logging options to get back any messages, and repost them here?

**Comment by arnavgupta06754** [comment]
My error and output files are empty as well.

**Comment by alexpreynolds** [comment]
If you can please post the full command you are running to schedule a job
via Slurm (i.e. with `sbatch` or `srun`), that would be useful.

If you can also please include the paths where you have installed BEDOPS,
along with the environment that your Slurm task is running within,
that would be great for debugging, as well.

**Comment by arnavgupta06754** [comment]
Thanks again for helping with this

Header
#!/bin/bash

#SBATCH --job-name=sam_to_bed
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem=64gb
#SBATCH --time=00:30:00
#SBATCH --partition=shas
#SBATCH --output=/scratch/summit/agupta06\@xsede.org/smAEC_ATAC/e_o/sam_to_bed.%j.out
#SBATCH --error=/scratch/summit/agupta06\@xsede.org/smAEC_ATAC/e_o/sam_to_bed.%j.err 

#Bedops is installed under my conda environment, so I call the conda
source conda-start
conda activate /projects/agupta06@xsede.org/applications/conda/env/Arnav_env

#set my input and output directories which I have excluded, and then:
sam2bed < ${INDIR}/Sm25_ATACseq-Ctrl1_R1.trimmed.sam > ${OUTDIR}/Sm25_ATACseq-Ctrl1_R1.reads.bed

#Sm25_ATACseq-Ctrl1_R1.trimmed.sam was generated from hisat2 alignment of my trimmed fastq file, I had ~85% read alignment and I have converted this file to .bam and viewed it on the igv browser so I know its legit

In my command line, I then submit my job to slurm using the command
$sbatch sam_to_bed.slurm

and then I wait, the job goes off my squeue and then I look in the output directory and there is a file created as the name I specified but it is empty, as are my error and output files in my e_o directory

**Comment by arnavgupta06754** [comment]
My bedops directory is here:
/projects/agupta06@xsede.org/applications/conda/env/Arnav_env/bin

**Comment by alexpreynolds** [comment]
Can you install BEDOPS directly from source code: https://bedops.readthedocs.io/en/latest/content/installation.html#installation-via-source-code

I don't know much lately about how Anaconda compiles our toolkit, and I've run into problems where binaries compiled with it may not work correctly. 

Building binaries from source would be a good way to help isolate the problem to the `convert2bed` binary in the conda package (or it could help suggest if the problem is elsewhere).

**Comment by alexpreynolds** [comment]
I haven't heard back, so I'm going to close this up. Please feel free to follow up if I can help further.
