### ISSUE TITLE
Start coordinate is too large - vcftobed conversion

### ISSUE THREAD

**Issue by asmariyaz23** [bedops/bedops#237]
While trying to convert vcf to bed I came across the following error:

```
vcf2bed < trimmed.FAM1_MU006.nanovar.pass.vcf
Start coordinate is too large.  Max decimal digits allowed is 12 in BEDOPS.Constants.hpp.  See line 17640 in -.
```

Could you please help me understand what I maybe doing wrong here?

**Comment by alexpreynolds** [comment]
Can you post your VCF somewhere where I can download it? I can examine it on this side.

**Comment by asmariyaz23** [comment]
@alexpreynolds Here it is:
[trimmed.trial.nanovar.pass.vcf.tar.gz](https://github.com/bedops/bedops/files/4434263/trimmed.trial.nanovar.pass.vcf.tar.gz)

I need to run the bedmap tool after converting this vcf to bed file.

**Comment by alexpreynolds** [comment]
Something seems odd with your VCF file, when looking at unsorted output:

```
$ convert2bed --input=vcf --output=bed --do-not-sort < trimmed.FAM1_MU006.nanovar.pass.vcf > /tmp/trimmed.FAM1_MU006.nanovar.pass.vcf.unsort.bed
```

Then:

```
$ head -17640 /tmp/trimmed.FAM1_MU006.nanovar.pass.vcf.unsort.bed | tail -1
chr9_KI270720v1_random  18446744073709551615    0       nv_SV28401-R746M        3.5     N       N]chr9:41223567]        PASS    SVTYPE=BND;END=1;SVLEN=.;SR=2;NN=0.555;SV2=TLO  GT:DP:AD        1/1:2:0,2
```

That `18446744073709551615` value is an unsigned equivalent of the signed `-1`.

Going back to the original VCF:

```
$ grep -wF chr9_KI270720v1_random trimmed.FAM1_MU006.nanovar.pass.vcf
##contig=<ID=chr9_KI270720v1_random,length=39050>
chr9    41223567        nv_SV28401-R746M        N       [chr9_KI270720v1_random:0[N     3.5     PASS    SVTYPE=BND;END=41223568;SVLEN=.;SR=2;NN=0.555;SV2=TLO   GT:DP:AD        1/1:2:0,2
chr9_KI270720v1_random  0       nv_SV28401-R746M        N       N]chr9:41223567]        3.5     PASS    SVTYPE=BND;END=1;SVLEN=.;SR=2;NN=0.555;SV2=TLO  GT:DP:AD        1/1:2:0,2
```

This seems to be the relevant line:

```
chr9_KI270720v1_random  0       nv_SV28401-R746M        N       N]chr9:41223567]        3.5     PASS    SVTYPE=BND;END=1;SVLEN=.;SR=2;NN=0.555;SV2=TLO  GT:DP:AD        1/1:2:0,2
```

VCF uses a 1-based index, which I think means that a variant shouldn't start with a zero position — but this one does. Unless I'm missing something, I think the VCF file may need to be looked at.

I'm going to close this up, but please let me know if I'm wrong in some way and we can reopen the discussion.
