### ISSUE TITLE
bedextract doesn't work

### ISSUE THREAD

**Issue by PanZiwei** [bedops/bedops#245]
Hi,
I am trying to use `bedextract` function but I got nothing after submitting `bedextract chr1 APL.bed` in a shell script.

But `bedextract --list-chr APL.bed` worked and printed all the chromosome information.

Here is an example for my `.bed` file.
```
(base) [c-panz@sumner080 BS_seq_ONT_merge]$ head -5 APL.bed
chr1	 28660	28660	CpG_Shores	APL	0.0	DeepSignal	0.0
chr1	 28660	28660	CpG_Shores	APL	0.0	DeepSignal	66.7
chr1	 28677	28677	CpG_Shores	APL	0.0	DeepSignal	0.0
chr1	 28677	28677	CpG_Shores	APL	0.0	DeepSignal	0.0
```

Here is the software version: 
```
# Name                    Version                   Build  Channel
bedops                    2.4.39               hc9558a2_0    bioconda
```

Do you know how can I solve the problem? 

Thank you so much for your help!

**Comment by alexpreynolds** [comment]
It looks like the file `APL.bed` has elements where the start and stop positions are identical, which is not correct BED input.

You can verify this by sorting your file with BEDOPS `sort-bed`. You should see an error that looks like the following:

```
$ sort-bed APL.bed > APL.sorted.bed
Error on line 1 in -. Genomic end coordinate is less than (or equal to) start coordinate.
```

These look like they might be Illumina probes? I think those are one-based. To fix this, you'll likely need to subtract one base from the start position, and to be safe, apply the correct sort order on your data. You could do something like this:

```
$ awk -v FS="\t" -v OFS="\t" '{ $2 = $2 - 1; print $0; }' APL.bed | sort-bed - > APL.zeroBasedIndex.sorted.bed 
```

Assuming there are no other issues, you could then use `APL.zeroBasedIndex.sorted.bed` with `bedextract`.

I'm going to close this up, but if this doesn't work, feel free to follow up with the commands you are running, and please attach the file you are working with.
