### ISSUE TITLE
Problem with starch

### ISSUE THREAD

**Issue by cadley-nyulangone** [bedops/bedops#248]
I am having a problem with the starch statement. I am using bedops version 2.4.37

I have a simple, 1-line, tab delimited bedfile: "jctest.bed"

It looks like this

 somechrom 0 1 . 0

I can't display them here, but those 5 fields are delimited by tabs.

I turn that bed file into a starch file like this

`starch jctest.bed > jctest.starch`

When I unstarch that file I get

 `unstarch jctest.starch`
`somechrom 0 1 . 0`

That is expected behavior. But now I change "somechrom" to "somechrom.01", so jctest.bed now looks like this

somechrom.01 0 1 . 0

I starch it, then unstarch it

`starch jctest.bed > jctest.starch`
`unstarch jctest.starch`
` somechrom 0 1 . 0`

The ".01" suffix has disappeared ! This happens whenever a suffix of any kind, including character suffixes, is placed after a period in the chrom name field of the bed file.

Is this a known behavior? Intended? Seems undesirable.

**Comment by alexpreynolds** [comment]
Thanks for the report; this does look like an interesting bug, probably related to how this field is parsed. 

Until I can fix this, it appears an underscore or hyphen works and may be a usable replacement for the dot character.

**Comment by cadley-nyulangone** [comment]
Thanks Alex.  It seems to happen here in starchMetadataHelpers.c :
<pre>
                        /* read chromosome name */
                        strncpy(recTokBuf, token, strlen(token) + 1);
                        for (recTokBufIdx = 0; recTokBufIdx < strlen(recTokBuf); recTokBufIdx++) {
                            if (recTokBuf[recTokBufIdx] == '.') {
                                recTokBuf[recTokBufIdx] = '\0';
                                break;
                            }
                        }
</pre>
Not sure what the motivation for doing it was.

**Comment by alexpreynolds** [comment]
Fixed in commit 7cd696ad
