### ISSUE TITLE
bedops breaks with >1000 files

### ISSUE THREAD

**Issue by stevekm** [bedops/bedops#249]
I have a directory of .bed files like this;

```
$ ls -1 inputs_dir/ | head
_maf2bed_merged.001004a5-9a67-4b4e-bdf5-dd82d21fb660.bed
_maf2bed_merged.0021e6b6-e03d-4b53-8b5b-5d4601059f25.bed
_maf2bed_merged.002f2502-918c-4b73-8359-b31a493f9c15.bed
_maf2bed_merged.0034c895-885c-4ef9-9aec-10ecc73ee904.bed
_maf2bed_merged.00373eb1-803f-4f3f-ba99-9a6d9c08c185.bed

$ ls -1 inputs_dir/ | wc -l
5000
```

And I save the paths to the files in a list like this;

```
$ find inputs_dir/ -type f > files.txt

$ wc -l files.txt
5000 files.txt

$ head files.txt
inputs_dir/_maf2bed_merged.afb9f671-d87b-4c47-bf49-f5754d564595.bed
inputs_dir/_maf2bed_merged.99295d64-ad45-4eef-8637-214e0588c2a9.bed
inputs_dir/_maf2bed_merged.b8776bb7-ff89-433b-8a04-cf670cec568d.bed
inputs_dir/_maf2bed_merged.e66ae891-68cc-43b2-96e2-b249f93c2826.bed
inputs_dir/_maf2bed_merged.567d755e-b4e1-4bd5-af19-202e99d83366.bed
```

If I run `bedops -m` like this, with batches of 1000 files, it works fine:

```
$ parallel -a files.txt --jobs 1 -n 1000 bedops -m {} ">" merged.{#}.bed

$ ll
-rw-r--r--     1 steve ci 114K Feb  9 13:59 merged.1.bed
-rw-r--r--     1 steve ci 116K Feb  9 13:59 merged.2.bed
-rw-r--r--     1 steve ci 116K Feb  9 13:59 merged.3.bed
-rw-r--r--     1 steve ci 115K Feb  9 13:59 merged.4.bed
-rw-r--r--     1 steve ci 115K Feb  9 13:59 merged.5.bed
```

However, if I try to use more files, `bedops` starts giving errors that it cannot see some of the files;

```
$ parallel -a files.txt --jobs 1 -n 1100 bedops -m '{}' '>' 'merged.{#}.bed'
May use bedops --help for more help.

Error: Unable to find file: inputs_dir/_maf2bed_merged.e5bb69ea-eae6-41f3-b5dd-2c68093e3253.bed
May use bedops --help for more help.

Error: Unable to find file: inputs_dir/_maf2bed_merged.3c9c264c-829f-4000-b9de-05db52816b9a.bed
May use bedops --help for more help.

Error: Unable to find file: inputs_dir/_maf2bed_merged.95c89d08-8f76-42ac-a245-478056c1545c.bed
May use bedops --help for more help.

Error: Unable to find file: inputs_dir/_maf2bed_merged.97e55467-7dda-450b-abaa-4e4c4d7dd542.bed
```

But the input files all exist;

```
$ ll inputs_dir/_maf2bed_merged.e5bb69ea-eae6-41f3-b5dd-2c68093e3253.bed
-rw-r--r-- 1 steve ci 202 Feb  9 12:49 inputs_dir/_maf2bed_merged.e5bb69ea-eae6-41f3-b5dd-2c68093e3253.bed
```

Any idea what is going wrong with `bedops` when you pass it >1000 input bed files?

Using 

```
$ bedops --version
bedops
  citation: http://bioinformatics.oxfordjournals.org/content/28/14/1919.abstract
            https://doi.org/10.1093/bioinformatics/bts277
  version:  2.4.39 (typical)
  authors:  Shane Neph & Scott Kuehn

$ parallel --version
GNU parallel 20201122
Copyright (C) 2007-2020 Ole Tange, http://ole.tange.dk and Free Software
Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
GNU parallel comes with no warranty.
```

**Comment by alexpreynolds** [comment]
With further testing, I suspect you'll find things break at more than 1021 files, specifically.

This is not a bug with `bedops`, nor is it really a bug, per se, but it is a default limit on the number of file descriptors or "handles" that a Unix process can work with in Linux (and with Mac OS X). 

The default limit is usually 1024. Three file descriptors are reserved for standard input, standard output, and standard error file streams. That leaves you 1021.

If you have root-level access to your system, you can raise this so-called "soft" limit up to the operating system's "hard" limit, with caveats:

- https://unix.stackexchange.com/a/84244/38132
- https://unix.stackexchange.com/questions/29577/ulimit-difference-between-hard-and-soft-limits

You might read those links and try out `ulimit` to adjust the maximum number of file descriptors.

If you don't have root access, you'll need to work around the OS limit and work on files in batches. I don't have a ready-made solution for that; this is a limitation you'd run into with any Unix tool.

If you raise the limits and you still run into problems, feel free to follow up with some more details about your system. But from prior experience, I suspect this is your issue.

**Comment by stevekm** [comment]
Ok thanks, I was using `parallel --xargs` under the impression that it would take care of handling the batch size, but I guess its only looking at the system CLI arg limit. I did not realize that Bedops is opening all file handles simultaneously. That makes more sense and I think the solution then for this case is to just limit the number of args per job with `parallel -n 500` or so

**Comment by alexpreynolds** [comment]
I'm not entirely sure what `parallel` is used for here, but if `--xargs` behaves like Unix `find`, then passing 1100 files to `bedops -m` will require 1101 file descriptors — 1100 for the files you're opening and one more for the file you're writing to.

To generalize this, perhaps look into using `split` on `files.txt` to make files that are always less than 1021 lines in length. 

- https://man7.org/linux/man-pages/man1/split.1.html

Run `bedops -m` on each split file. This step could be done via `parallel`, running each split-merge task in its own thread (if your disk storage can handle concurrent operations — some SSDs can do this). Then run `bedops -m` on each merged-split result to get a final result.
