### ISSUE TITLE
issue with bedops --merge

### ISSUE THREAD

**Issue by Marjorie-Liebling** [bedops/bedops#251]
Hi, 

I'm running `bedops --merge`  with version 2.4.39 on two sorted bedfiles but the output is not sorted. 
For example: 
### temp1.bed
```
chr9	138217345	138217420
chr9	138217729	138217827
chr9	138218468	138218583
chr9	138277018	138277022
chr10	9495	9539
chr10	10053	10119
chr10	10260	10286
chr10	13109	13147
chr10	28103	28130
chr10	35178	35326
chr10	38821	38827
```

### temp2.bed
```
chr9    138216681       138216735
chr9    138217266       138217387
chr9    138217743       138217788
chr9    138218102       138218128
chr9    138218535       138218573
chr9    138218694       138218719
chr10   12586   12607
chr10   27868   27885
chr10   46724   46728
chr10   47283   47287
chr10   47425   47459
```
### Merged BED
`bedops --merge temp1.bed temp2.bed`
```
chr9	138216681	138216735
chr9	138217266	138217420
chr9	138217729	138217827
chr9	138218102	138218128
chr9	138218468	138218583
chr9	138218694	138218719
chr10	12586	12607
chr10	27868	27885
chr10	46724	46728
chr10	47283	47287
chr10	47425	47459
chr9	138277018	138277022
chr10	9495	9539
chr10	10053	10119
chr10	10260	10286
chr10	13109	13147
chr10	28103	28130
chr10	35178	35326
chr10	38821	38827
```

Do you know what is going on here?

Many thanks,
Marjorie

**Comment by alexpreynolds** [comment]
Your inputs are not sorted per `sort-bed` (https://bedops.readthedocs.io/en/latest/content/reference/file-management/sorting/sort-bed.html). Try the following:

```
$ bedops --merge <(sort-bed temp1.bed) <(sort-bed temp2.bed)
```

So long as your inputs are sorted, the output will be sorted correctly. 

I'm going to close this up. If you still run into a bug, feel free to follow up.

**Comment by Marjorie-Liebling** [comment]
Thank you so much for your quick reply. This works nicely. I thought it was a positional sort, not a lexicographical one.
