### ISSUE TITLE
bedmap uses >150GB ram on an input file of 10GB

### ISSUE THREAD

**Issue by yonniejon** [bedops/bedops#254]
I am using bedmap version:  2.4.38 . 

I run the following:

bedmap --echo --echo-map-id-uniq --skip-unmapped gencode.v29.gene.bed $f > $out_file

where gencode.v29.gene.bed is gecode v 29 gtf file after running gtf2bed. $f is a bed file which is 10GB and gencode.v29.gene.bed is 0.01GB . 

Looking at ram usage I am getting out of memory errors and I see >149.4 GB used (available 150). Does this make sense?

**Comment by yonniejon** [comment]
I can provide the two input files if it will help

**Comment by yonniejon** [comment]
I increased allowed memory to 300GB and that was fully used as well. I will try running with the --min-memory flag

**Comment by alexpreynolds** [comment]
Is $f sorted with sort-bed?

**Comment by yonniejon** [comment]
yes it is

**Comment by yonniejon** [comment]
running with --min-memory finishes quickly and uses <10Gb memory

**Comment by alexpreynolds** [comment]
If you are able to share the input files, I'd be interested to take a look at them. In any case, I'm glad that this option worked.

**Comment by yonniejon** [comment]
Yes- I will upload it someplace. maybe google drive and then share. sorry about delay

**Comment by alexpreynolds** [comment]
I'm going to close this up as resolved. Please feel free to follow up, if you like.
