### ISSUE TITLE
Document which fields sort-bed --unique filters BED elements by all fields, or only some fields. 

### ISSUE THREAD

**Issue by alexlenail** [bedops/bedops#259]
Documentation is slightly vague: "--unique can be used to print only unique BED elements (similar to "sort -u")." Is a BED element defined as the entire row, or just the chr/start/stop/name/score? I did `sort-bed | uniq > out.bed` just in case.

**Comment by alexpreynolds** [comment]
The `sort-bed` tool will sort on the entire line to get a deterministic sort. You can use tests to verify this, e.g.:

```
$ cat test.bed
chr1	842320	842327	A	0.123	+
chr1	842328	842330	B	0.234	+
chr1	842328	842330	B	0.234	-
chr1	855426	855427	C	0.456	+
chr1	855426	855427	C	0.567	+
chr1	855739	855740	D	0.123	+
chr1	855739	855740	D	0.123	+
```

Then:

```
$ sort-bed test.bed
chr1	842320	842327	A	0.123	+
chr1	842328	842330	B	0.234	+
chr1	842328	842330	B	0.234	-
chr1	855426	855427	C	0.456	+
chr1	855426	855427	C	0.567	+
chr1	855739	855740	D	0.123	+
chr1	855739	855740	D	0.123	+
```

To get unique elements:

```
$ sort-bed -u test.bed
chr1	842320	842327	A	0.123	+
chr1	842328	842330	B	0.234	+
chr1	842328	842330	B	0.234	-
chr1	855426	855427	C	0.456	+
chr1	855426	855427	C	0.567	+
chr1	855739	855740	D	0.123	+
```

Or:

```
$ sort-bed test.bed | uniq
chr1	842320	842327	A	0.123	+
chr1	842328	842330	B	0.234	+
chr1	842328	842330	B	0.234	-
chr1	855426	855427	C	0.456	+
chr1	855426	855427	C	0.567	+
chr1	855739	855740	D	0.123	+
```

Using `sort-bed -u` should be slightly faster, as the lines being compared are already in memory.

Perhaps it can be made more prominent, but the [documentation](https://bedops.readthedocs.io/en/latest/content/reference/file-management/sorting/sort-bed.html) does describe this:

> To make the sort order unambiguous, a lexicographical sort is applied on fourth and subsequent columns, where present in the input BED dataset.

Hopefully this addresses your question. Please feel free to follow up, if not.
