### ISSUE TITLE
BEDOPS v2.4.40 linux .tar.bz2 release

### ISSUE THREAD

**Issue by epaule** [bedops/bedops#260]
the linux tarball (bedops_linux_x86_64-v2.4.40.tar.bz2) is not compressed with bzip2, so my update script breaks with a bzip2 error: bzip2: (stdin) is not a bzip2 file

(which is from tar). I commented out my -j from the untarring, but could you compress it (or change the suffix if not)?

**Comment by alexpreynolds** [comment]
Sorry for the inconvenience and thanks for filing the issue. The release and checksum are now correct.

**Comment by ygao-unsw** [comment]
Hi there,

Just a comment that the tarball is not bzipped for the v.2.4.42 release either. Removing the `j` option in tar still valid as workaround.

Cheers
