### ISSUE TITLE
error in vcf2bed

### ISSUE THREAD

**Issue by ketkijoshi278** [bedops/bedops#261]
Hello,
I am trying to convert vcf file to bed. but I am getting some error.
The command:
vcf2bed < GEUVADIS.chr22.genotype.vcf > chr22_sorted-foo.vcf.bed
The error:
Error: Could not find newline in intermediate buffer; check input [14823 | 26286 | 41109]
       Please check that your input contains Unix newlines (cat -A) or increase TOKENS_MAX_LENGTH in BEDOPS.Constants.hpp and recompile BEDOPS.
convert2bed
  version:  2.4.39

**Comment by alexpreynolds** [comment]
Please see discussion thread and potential solution here: 

https://github.com/bedops/bedops/issues/230#issuecomment-553272195

**Comment by ketkijoshi278** [comment]
Hey, I tried using the above solution but I am still getting the error.
chr22.bed.log file is getting created but its showing this content 
Error: Could not find newline in intermediate buffer; check input [14823 | 26286 | 41109]
       Please check that your input contains Unix newlines (cat -A) or increase TOKENS_MAX_LENGTH in BEDOPS.Constants.hpp and recompile BEDOPS.
convert2bed
  version:  2.4.39
  author:   Alex Reynolds

**Comment by alexpreynolds** [comment]
What is the output of `convert2bed --version`?

**Comment by ketkijoshi278** [comment]
version:  2.4.40
  author:   Alex Reynolds

**Comment by alexpreynolds** [comment]
Can you please post the full output?

**Comment by ketkijoshi278** [comment]
./convert2bed --version
convert2bed
  version:  2.4.40
  author:   Alex Reynolds
This is the output. I am not getting anything else

**Comment by alexpreynolds** [comment]
I'm not sure why you are not seeing the full version information. 

In any case, you could perhaps try the precompiled binaries in the Releases page: 

https://github.com/bedops/bedops/releases

If you're on Linux, you can use the instructions here to extract and put items in a useful directory:

https://bedops.readthedocs.io/en/latest/content/installation.html#linux

Once installed, you should then be able to use the `switch-BEDOPS-binary-type` helper script to switch between `typical` and `megarow` (and `float128`, though probably not useful here):

```
$ switch-BEDOPS-binary-type --help
Switch the BEDOPS binary build to typical, megarow, or float128
Usage: switch-BEDOPS-binary-type [ --help ] [ --typical | --megarow | --float128 ] [ <binary-directory> (optional) ]
```

Using the `megarow` variant of this kit will support longer lines.

**Comment by alexpreynolds** [comment]
I'll assume that the `megarow` binaries helped. Please feel free to follow up with more detail if that's not the case, and I'll reopen.

**Comment by ketkijoshi278** [comment]
Hey, Can you please let me know whats wrong with this command.
convert2bed --input=[vcf] -i GEUVADIS.chr22.genotype_updated2.vcf --output=[bed]
I shifted to megarow. But when i write the command vcf2bed it doesn't generate an output file

**Comment by ketkijoshi278** [comment]
I am able to do so. 
Thank you for your help.
I have one more doubt. I have a file whose content is:
CHROM_POS
chr10_100009635
chr10_100187980
chr10_100229692
chr10_100267650
chr10_100269675
chr10_100279430
chr10_100285899
chr10_100286623
chr10_100293127
chr10_100341409
chr10_100372754
chr10_100489127
chr10_100519538
chr10_100529321
chr10_100529986
chr10_100536079
chr10_100912491
chr10_100912961
chr10_100969364
chr10_100972002
chr10_100985749
chr10_100986746
chr10_100987072
chr10_100987606
chr10_1009926
chr10_100996986
chr10_101025292
chr10_101031042
chr10_101032154
chr10_101035974
chr10_101062164
Its content is chrom_pos.
Can vcf2bed will be able to convert this to bed format.
