### ISSUE TITLE
Version 2.4.40 changed after release

### ISSUE THREAD

**Issue by amadejpapez** [bedops/bedops#262]
I just fixed the bedops in Homebrew package manager as the checksum was wrong for the latest version. Version 2.4.40 was released on July 22 and the package in Homebrew was updated the same day. Looking at the [v2.4.40](https://github.com/bedops/bedops/commits/v2.4.40) tag seems like another commit was added 5 days after release that broke the checksum. Was this intentional?

Related Homebrew PR: [#88428](https://github.com/Homebrew/homebrew-core/pull/88428)

**Comment by alexpreynolds** [comment]
Yes, I added a file a few days later. Thanks for updating the homebrew package.

**Comment by amadejpapez** [comment]
Thank you for quick confirmation. :)
