### ISSUE TITLE
Mysterious error in bedops -u

### ISSUE THREAD

**Issue by alexlenail** [bedops/bedops#263]
`bedops -u ENCFF386ZWO.bed`

works fine

`bedops -u *.bed` 

fails with message: 

```
May use bedops --help for more help.

Error: Unable to find file: ENCFF386ZWO.bed
```

**Comment by alexlenail** [comment]
Is there a maximum number of bed files you're allowed to pass in perhaps?

**Comment by alexpreynolds** [comment]
I'm not sure I have enough to go on here, but your power-of-two observation does suspiciously sound like a limit on file descriptors, which is an operating system limit not to do with BEDOPS. Please see the discussion and potential solutions here: https://github.com/bedops/bedops/issues/249

If you have more information on your host OS and version, and what the file descriptor limits are (see: https://unix.stackexchange.com/questions/84227/limits-on-the-number-of-file-descriptors) that would be helpful.

**Comment by alexlenail** [comment]
osx monterey

solved with `ulimit -n 10240` thanks :)
