### ISSUE TITLE
`bedops -u *.bed | bedmap --max-element` does not select max element

### ISSUE THREAD

**Issue by alexlenail** [bedops/bedops#264]
This is more of a support request/usage question. Is there a better venue for those? 

I want to select the strongest peak among replicate ChIP experiments. Inspired by these [docs](https://bedops.readthedocs.io/en/latest/content/usage-examples/multiple-inputs.html), I wrote

`bedops -u *.bed | bedmap --fraction-both 0.5 --max-element - > out.bed`

however, the output contains every peak from the input beds, including lines like:
```
chr1	778452	778788	POLR2A	1000.000000	.	151.31918	-1.0	4.88767	170
chr1	778452	778788	POLR2A	1000.000000	.	151.31918	-1.0	4.88767	170
chr1	778452	778788	POLR2A	1000.000000	.	151.31918	-1.0	4.88767	170
chr1	778452	778788	POLR2A	1000.000000	.	151.31918	-1.0	4.88767	170
```

What am I doing wrong?

**Comment by alexpreynolds** [comment]
You might be running into the following situation, maybe not. But it is something to think about.

Consider the following three elements in a file called `A.bed`:

```
chr1    1000    2000    ABC     500
chr1    1500    2500    DEF     1000
chr1    2000    3000    GHI     750
```

You could run the following to get an answer:

```
$ bedops -u A.bed | bedmap --fraction-both 0.5 --max-element -
chr1    1500    2500    DEF     1000.000000
chr1    1500    2500    DEF     1000.000000
chr1    1500    2500    DEF     1000.000000
```

Note the duplication in the (correct) output.

You could run the following to explain why the output is correct:

```
$ bedops -u A.bed | bedmap --fraction-both 0.5 --echo --max-element -
chr1    1000    2000    ABC     500.000000|chr1 1500    2500    DEF     1000.000000
chr1    1500    2500    DEF     1000.000000|chr1        1500    2500    DEF     1000.000000
chr1    2000    3000    GHI     750.000000|chr1 1500    2500    DEF     1000.000000
```

For each of the three elements in `A`, there is some element elsewhere that overlaps it by the `--fraction-both 0.5` criteria. That element just happens to be the same for all three members of `A`.

To fix this problem, perhaps use `sort-bed --unique` to get only unique elements:

```
$ bedops -u A.bed | bedmap --fraction-both 0.5 --max-element - | sort-bed --unique -
chr1    1500    2500    DEF     1000.000000
```

**Comment by alexlenail** [comment]
Got it! I just didn't understand what `--max-element` does. Thanks @alexpreynolds !

**Comment by alexlenail** [comment]
As a follow up question: the [ENCODE narrowpeak](https://genome.ucsc.edu/FAQ/FAQformat.html#format12) files scores are not as informative as column 7: signalValue. Do you have a recommended way to get the max element over a different column? (Just rotate the columns?)

**Comment by alexpreynolds** [comment]
Yep, just permute or cut columns with `awk` or `cut` (for instance). You can pipe the result into BEDOPS tools.

**Comment by alexpreynolds** [comment]
> Got it! I just didn't understand what `--max-element` does. Thanks @alexpreynolds !

It's not so much what `--max-element` does, I think, but that `bedmap` does some specified operation (here, `--max-element`) on each element of the _reference file_. 

You could get the same answer back from each element. You could get different answers. But I think the key is to understand what the operation is working upon; using `--echo` can help troubleshoot these situations.

**Comment by alexpreynolds** [comment]
> Yep, just permute or cut columns with `awk` or `cut` (for instance). You can pipe the result into BEDOPS tools.

For instance, here's a simple example:

```
bedops -u *.bed | cut -f1-4,7 | bedmap ...
```

The `cut -f1-4,7` statement makes a five-column BED file, with the fifth column derived from narrowPeak's column 7/signalValue field. The score value is in the fifth column, so `bedmap` can bed used with all the same score-based operations.
