### ISSUE TITLE
Build failures due to template const member functions updating object fields

### ISSUE THREAD

**Issue by jmarshall** [bedops/bedops#267]
C++ compilers have always generally rejected classes with const member functions that modify non-mutable object fields. However they have historically accepted such code when it is in a templated class that is never instantiated or the const member function in question is never instantiated.

Clang (from v11 or so onwards) no longer accepts such code even if the const member function is never used or instantiated.

So the following in _applications/bed/bedextract/src/ExtractRows.cpp_ causes a build failure with recent Clang:

```c++
  template <typename ValueType>
  struct Cache {
    Cache() : empty_(true)
      { }

    template <typename T>
    void operator()(const T* t) {
      empty_ = false;
    }

    bool Empty() const { return empty_; }
    void Clear() const { empty_ = true; }

  private:
    bool empty_;
  };
```

The `Clear()` method is currently never used, so the fix would be either to remove it or to make it non-`const` (hence `void Clear() { empty_ = true; }`) as it is clearly not really a const function.

A similar build failure is caused by _interfaces/general-headers/utility/BitMonitor.hpp_'s `BSet::next_set()`, which attempts to update the `_open` private member field. `BSet` is used only by `PooledCharMemory2` which is itself unused, so one fix would be to remove both classes. Alternatively, this may be an instance in which the `BSet::_open` field should be marked as `mutable`.

**Comment by alexpreynolds** [comment]
Patched in 2bd7994e. Thanks for the report and to Shane Neph for additional feedback. I am running Clang v13.1.6 (well past v11), so I'm not sure why this didn't return any errors on my end. In any case, I'll close this up, and please feel free to follow up if you still run into errors.

**Comment by jmarshall** [comment]
Apple Clang version numbers diverged from (and are inflated compared to) upstream LLVM version numbers years ago. [Wikipedia's table](https://en.wikipedia.org/wiki/Xcode#Xcode_11.x_-_14.x_(since_SwiftUI_framework)_2) suggests they have since converged somewhat, but testing this particular behaviour shows otherwise.

That change LGTM. Note that CI on this branch is failing because [ubuntu-16.04 is long gone](https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/); suggest updating _.github/workflows/main.yml_ to use `ubuntu-latest` instead.

**Comment by alexpreynolds** [comment]
Thanks for the Clang info, makes sense now. The action should be an easy change, thanks.
