### ISSUE TITLE
Add 2.4.40 to bioconda?

### ISSUE THREAD

**Issue by russellsmithies** [bedops/bedops#269]
Can we get the latest release pushed to bioconda please? Currently the latest available via conda is  2.4.39

thanx :-)

**Comment by alexpreynolds** [comment]
I'm working on a 2.4.41 release, hopefully this week, and I'll work on a bioconda push when that is out.

**Comment by alexpreynolds** [comment]
https://github.com/bioconda/bioconda-recipes/pull/35823

**Comment by jmarshall** [comment]
(For the record, bioconda/bioconda-recipes#35647, which updated bioconda's package to 2.4.40, was merged about a day after this issue was opened.)

**Comment by alexpreynolds** [comment]
Sorry @jmarshall , the timing of 2.4.41 just happened to align with your recent push. Thanks for your quick assistance!
