### ISSUE TITLE
"Error: Invalid WIG line" when using convert2bed on wiggle file

### ISSUE THREAD

**Issue by eggrandio** [bedops/bedops#273]
Hello, 

I am trying to convert a wiggle file to bed but I get a "Error: Invalid WIG line 7" error message.

I have generated the wiggle file with wiggletools by averaging several bigwig files:

```
bw_files=$(find *.bw | paste -s)
wiggletools mean $bw_files > test_mean.wig
```

This wiggle file seems to be in a weird format (bedGraph mixed with wiggle? also, zero-indexed):

```
head -10 test_mean.wig
SL4.0ch00       0       63      0.000000
SL4.0ch00       63      67      0.037542
SL4.0ch00       67      87      0.091239
SL4.0ch00       87      114     0.128781
fixedStep chrom=SL4.0ch00 start=115 step=1
0.091239
SL4.0ch00       115     138     0.037542
SL4.0ch00       138     145     0.000000
SL4.0ch00       145     149     0.037542
SL4.0ch00       149     153     0.075084
```
When I try to use convert2bed I get the error message:

```
convert2bed --input=wig --output=bed  --zero-indexed < test_mean.wig > test_mean.bed
Error: Invalid WIG line 7
```
I guess its an error in the formatting of the wiggle file.

I found a similar [issue](https://github.com/bedops/bedops/issues/239) where they comment that --multisplit fixes the problem, but I cannot get it to work, as at least in my version of convert2bed, --multisplit option is not documented.

```
convert2bed --input=wig --output=bed  --zero-indexed --multisplit=1 < test_mean.wig > test_mean.bed
Error: Invalid WIG line 7
```

Best,

**Comment by alexpreynolds** [comment]
Hmm. That doesn't look like WIG input, to me. 

Please take a look here: https://uswest.ensembl.org/info/website/upload/wig.html

Or here: https://genome.ucsc.edu/goldenPath/help/wiggle.html

It's possible this is some weird non-Wiggle output where bedGraph is embedded into a file with a `.wig` extension.

I'll close this up, but feel free to follow up if I'm wrong about this, and if you can post the relevant file somewhere.

**Comment by hanrong498** [comment]
Hi! 

I have encountered the same issue when trying to write the output in to a bedGraph using `> test_mean.bedGraph`. This problem is solved when I use `wiggletools write_bg test_mean.bedGraph`

Hope it helps!
Hanrong

**Comment by alexpreynolds** [comment]
I'm not sure it is Wiggle format. Maybe there are other tools that will convert this.
