### ISSUE TITLE
gff2bed fails with "Non-numeric start coordinate. "

### ISSUE THREAD

**Issue by shbrainard** [bedops/bedops#275]
I am running gff2bed 2.4.41 and get the error:

```
Warning: If your Wiggle data is a significant portion of available system memory, use the --max-mem and --sort-tmpdir options, or use --do-not-sort to disable post-conversion sorting. See --help for more information.
Non-numeric start coordinate.  See line 1085469 in -.
(remember that chromosome names should not contain spaces.)
Error: Stage [Sorted BED to stdout] failed -- exit status [256 | 1]
```

This line is no different from every other line is this GFF file.  It is tab delimited and generated by AUGUSTUS.  It is specifically:

`Camer_chr1  AUGUSTUS    tts 23621380    23621380    .   -   .   transcript_id "g2302.t1"; gene_id "g2302";
`

Any suggestions appreciated

**Comment by alexpreynolds** [comment]
If you can post the GFF file where I can look at it, I'll try to reproduce it here and see what's up, when I can.

**Comment by alexpreynolds** [comment]
Also, if you can please post a little about your host environment and what command you're running, that would be helpful in testing on this end.

**Comment by shbrainard** [comment]
[Camericana_Winkler_gene_models.gff.gz](https://github.com/bedops/bedops/files/10670085/Camericana_Winkler_gene_models.gff.gz)

Thanks, and absolutely!  I've attached it here.  I'm on macOS 12.6.3.

I was following [this tutorial](https://darencard.net/blog/2019-01-25-UCSC-genome-track-setup/), and was running specifically this command: 

`cat Camericana_Winkler_gene_models.gff | gff2bed | awk -F "\t|;" -v OFS="\t" '{ print $1, $2, $3, $11 }' | sed -e 's/%2528/\(/g' -e 's/%2529/\)/g' -e 's/%252F/\//g' -e 's/Name=//g' | sort-bed - > Camericana_gene_models.bed4`

So essentially, I was just piping the entire file to gff2bed with default parameters.

**Comment by alexpreynolds** [comment]
Sorry for the late reply. I patched the parser for AUGUSTUS-formatted GFF entries in commit `1c671c7f`. 

I don't have an exact date on when this will merge into the main branch, but this is available currently from branch `v2p4p42`.

Another option is to strip out lines which start with AUGUSTUS headers, and then sort:

```
gunzip -c Camericana_Winkler_gene_models.gff.gz | gff2bed --do-not-sort - | grep -v '# ' | sort-bed - > Camericana_Winkler_gene_models.gff.bed
```

The patched version includes modified header entries that do not clash with the sort step.
