### ISSUE TITLE
Semicolon in 'gene_name' or 'transcript_name' breaks gtf2bed

### ISSUE THREAD

**Issue by NanoCoreUSA** [bedops/bedops#276]
I'm designing a tool that ideally is able to handle any GTF file downloaded from Ensembl and am using BEDOPS gtf2bed to convert them to BED files. I've recently noticed that if there is a semicolon in the 'gene_name' or 'transcript_name' attribute that the tool is unable to parse the GTF file correctly resulting in an error (see below). 

`cat test.gtf`
`1	araport11	transcript	26439556	26443007	.	+	.	gene_id "AT1G70210"; transcript_id "AT1G70210.1"; gene_name "CYCD1;1"; gene_source "araport11"; gene_biotype "protein_coding"; transcript_name "CYCD1;1-201"; transcript_source "araport11"; transcript_biotype "protein_coding"; tag "Ensembl_canonical";`

`gtf2bed --attribute-key=gene_name < test.gtf > test.bed`
`Error: Could not parse ID from GTF gene_id attribute (malformed GTF at line [1]?)`

It seems to only be an issue when specifying the 'attribute-key'... I assume semicolons shouldn't be included in the name according to the GTF format spec since they are used as delimiters, but alas many Ensembl GTF files contain them so just wanted to bring it up (the above example is from the latest release for _Arabidopsis_...). 

I'm not sure what awk command to use since the delimiters are necessary...

**Comment by alexpreynolds** [comment]
It would be really nice if Ensembl would clean up their act and either put out correct files or change the specification to allow malformed GTF.

In any case, I'd need to extend the parser to look for a semi-colon character within quoted `gene_name` key-value pairs.

Thanks for the report. I'll leave this ticket open; I'm not sure exactly when I can get to this, but hopefully soon.

**Comment by NanoCoreUSA** [comment]
Just FYI, this is the awk command that I ended up using on the problematic GTFs before piping into the gtf2bed call to remove potential semicolons.

`
awk -F'"' -v OFS='"' '{{for(i=2; i<=NF; i+=2) gsub(";", "-", $i)}} 1'`
