### ISSUE TITLE
interpret output of infer_experiment.py

### ISSUE THREAD

**Issue by lalalagartija** [bedops/bedops#278]
Hi, 
Just a quick question. Can someone explain what "1++,1--,2+-,2-+" or "1+-,1-+,2++,2--" exacly means ? 
Thank you :)

The output : 
`PairEnd
0.20336934463411724

This is PairEnd Data
Fraction of reads failed to determine: 0.0274
Fraction of reads explained by "1++,1--,2+-,2-+": 0.2034
Fraction of reads explained by "1+-,1-+,2++,2--": 0.7693`

**Comment by alexpreynolds** [comment]
You might have a question about a different piece of software. I'll close this up for now. Feel free to follow up with more detail, otherwise.

**Comment by lalalagartija** [comment]
I found an answer somwhere else: https://rseqc.sourceforge.net/#infer-experiment-py
The 1++ means reand 1 is on strand + if read 1 is on strand +.    2+- means read 1 is on strand - if read 2 is on strand + ... and so on. 
Maybe you could clarify your documentation
