### ISSUE TITLE
vcf2bed; Segmentation fault 

### ISSUE THREAD

**Issue by PyunJung-Min** [bedops/bedops#279]
Hi! Thanks for the useful tools! 

I'm new to bedops and this is probably a basic question..

I tried following command and got the message, "Segmentaiton fault ${cmd}  ${option} -0<&0" 

wget -qO- ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606_b150_GRCh37p13/VCF/All_20170710.vcf.gz | vcf2bed --sort-tmpdir=/BiO/Access/home/pyunmaster/tmp --max-mem=2G - > hg19.dbSNP150.bed

Many thanks in advance !! 

Jung-Min

**Comment by alexpreynolds** [comment]
You will need to decompress the gzip'ed VCF file, first. Just add a `gunzip -c` step in the pipeline:

```
wget -qO- ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606_b150_GRCh37p13/VCF/All_20170710.vcf.gz | gunzip -c | vcf2bed --sort-tmpdir=/BiO/Access/home/pyunmaster/tmp --max-mem=2G - > hg19.dbSNP150.bed
```

Thanks for using the kit and feel free to follow up if this does not work for you.
