### ISSUE TITLE
bedmap issue 

### ISSUE THREAD

**Issue by PyunJung-Min** [bedops/bedops#280]
Hi Alex 

Thanks for the anwser of my previous question. It worked well. :) 

this time.. I have a question about bedmap command. 

I like to map rsid to chr-pos in my sumstat.
#1. I prepared "sumstat.bed" file using following command and looks like below.

awk -vOFS="/t" 'NR>1{n=split($0,a,/[:_]/); print a[1]"\t"a[2]-1"\t"a[2];}' PDGWAS.txt | sort-bed ->sumstat.bed

chr1    54590   54591   A       G       0.9938  -0.6797 0.8869  0.4435  527     472
chr1    54675   54676   T       C       0.3166  -0.0996 0.0656  0.1287  1169    968
chr1    79187   79188   T       G       0.0062  0.6704  0.8795  0.4459  527     472
chr1    82993   82994   A       G       0.9984  1.2614  1.8502  0.4954  527     472

#2. I prepared "hg19.dbSNP150.bed" file using command and looks like below.

wget -qO- ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606_b150_GRCh37p13/VCF/All_20170710.vcf.gz | gunzip -c | vcf2bed --sort-tmpdir=/BiO/Access/home/pyunmaster/tmp --max-mem=2G - > hg19.dbSNP150.bed

1       10018   10019   rs775809821     .       TA      T       .       RS=775809821;RSPOS=10020;dbSNPBuildID=144;SSR=0;SAO=0;VP=0x050000020005000002000200;GENEINFO=DDX11L1:100287102;WGT=1;VC=DIV;R5;ASP
1       10038   10039   rs978760828     .       A       C       .       RS=978760828;RSPOS=10039;dbSNPBuildID=150;SSR=0;SAO=0;VP=0x050000020005000002000100;GENEINFO=DDX11L1:100287102;WGT=1;VC=SNV;R5;ASP
1       10042   10043   rs1008829651    .       T       A       .       RS=1008829651;RSPOS=10043;dbSNPBuildID=150;SSR=0;SAO=0;VP=0x050000020005000002000100;GENEINFO=DDX11L1:100287102;WGT=1;VC=SNV;R5;ASP
1       10050   10051   rs1052373574    .       A       G       .       RS=1052373574;RSPOS=10051;dbSNPBuildID=150;SSR=0;SAO=0;VP=0x050000020005000002000100;GENEINFO=DDX11L1:100287102;WGT=1;VC=SNV;R5;ASP

#3. When I tried to map using following command,

bedmap --echo --echo-map-id --delim ‘\t’ sumstat.bed hg19.dbSNP150.bed > answer.bed

I got the following result in output file.
rs ID is not included and  just 't' in the end column is added. 

chr1    54590   54591   A       G       0.9938  -0.6797 0.8869  0.4435  527     472‘t’
chr1    54675   54676   T       C       0.3166  -0.0996 0.0656  0.1287  1169    968‘t’
chr1    79187   79188   T       G       0.0062  0.6704  0.8795  0.4459  527     472‘t’
chr1    82993   82994   A       G       0.9984  1.2614  1.8502  0.4954  527     472‘t’

Could you please see what I'm doing wrong? :)

Many thanks!

Jung-Min

**Comment by alexpreynolds** [comment]
Looks like the SNP file uses the Ensembl naming scheme for chromosomes (`1`, `2`, etc.) while your `sumstat.bed` file uses UCSC format (`chr1`, `chr2`, etc.). Both files have to use the same scheme for mapping to work.

You could insert an `awk` statement to prepend a `chr` to each line of the SNP input:

```
wget -qO- ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606_b150_GRCh37p13/VCF/All_20170710.vcf.gz | gunzip -c | vcf2bed --sort-tmpdir=/BiO/Access/home/pyunmaster/tmp --max-mem=2G - | awk -v FS="\t" -v OFS="\t" '{ print "chr"$0 }' > hg19.dbSNP150.bed
```

Then use `hg19.dbSNP150.bed` as before.

Alternatively, you could strip `chr` from each line of `sumstat.bed`. Whichever is easier or convenient may depend on what you're doing with the output, perhaps.

Feel free to follow up if you have any further issues.
