### ISSUE TITLE
Weird result on a specific file

### ISSUE THREAD

**Issue by pdeven** [bedops/bedops#283]
I am trying to overlap a file with itself ,
File i am trying to overlap with itself is sample.bed and the command i am using is
```
bedmap --max --echo-map-id --fraction-ref 0.9 --echo-ref-name --indicator sample.bed sample.bed | head
0.000000|1:866407-871286|1:866407-871286|1
NAN||1:948942-957856|0
NAN||1:1022870-1026999|0
NAN||1:1139767-1139876|0
NAN||1:1333965-1337646|0
```
it unusually produces this output, which shows no overlap as 0 at the last column
If a use a different file ,it will produce a correct output, 
```
bedmap --max --echo-map-id --fraction-ref 0.9 --echo-ref-name --indicator test.bed test.bed | head
test|1:896997-899570|1:896997-899570|1
test|1:1220939-1221054|1:1220939-1221054|1
test|1:1235877-1236082|1:1235877-1236082|1
test|1:1255824-1256483|1:1255824-1256483|1
```
This unexpected behaviour happens with only this file ie sample.bed , i am attaching both the files ,please help me to debug the issue
sharing gdrive folder link, where sample.bed and test.bed is present : [link](https://drive.google.com/drive/folders/1LArtClKinVvbyB58D-RxEvnRP7rZXX2K?usp=sharing)

**Comment by rsandstromUW** [comment]
sorting sample.bed with sort-bed produces a different order, but something else is going on as the overlaps are still weird:

```
bedmap --max --echo-map-id --fraction-ref 0.9 --echo-ref-name --indicator sorted.sample.bed sorted.sample.bed | head -4
0.000000|1:866407-871286|1:866407-871286|1
NAN||1:948942-957856|0
NAN||1:1022870-1026999|0
NAN||1:1139767-1139876|0
```

**Comment by alexpreynolds** [comment]
It does look like `sample.bed` is not sorted per `sort-bed`, which can give bad results:

```
$ sort-bed sample.bed > sample.sorted.bed
$ diff -qs sample.bed sample.sorted.bed
Files sample.bed and sample.sorted.bed differ
```

This is not an issue for `test.bed`:

```
$ sort-bed test.bed > test.sorted.bed
$ diff -qs test.bed test.sorted.bed 
Files test.bed and test.sorted.bed are identical
```

I'm looking to see if there may be other issues, but I would also recommend to make sure to start with sorted inputs.

**Comment by alexpreynolds** [comment]
In addition to sorting, another problem may be that you appear to have non-score data (i.e., strings) in what is expected to be the score column:

```
$ head sample.bed | cut -f5
test
test
test
test
test
test
test
test
test
test
```

Using the `--max` operator with `bedmap` requires UCSC-formatted BED data in the fifth column (something numerical) to find the maximum scoring element. I'm actually unsure what would happen if strings are passed into the score comparator, but I'd expect garbage and that appears to be what you're seeing, at least.

If the `--max` operator is removed, then output looks more like something that might be expected:

```
$ bedmap --echo-map-id --fraction-ref 0.9 --echo-ref-name --indicator <(sort-bed sample.bed) | head
1:866407-871286|1:866407-871286|1
1:948942-957856|1:948942-957856|1
1:1022870-1026999|1:1022870-1026999|1
1:1139767-1139876|1:1139767-1139876|1
1:1333965-1337646|1:1333965-1337646|1
1:1368601-1368678|1:1368601-1368678|1
1:1663882-1663972|1:1663882-1663972|1
1:1853714-1854948|1:1853714-1854948|1
1:1897798-1900282|1:1897798-1900282|1
1:1916813-1957193|1:1916813-1957193|1
```

You could use `awk` or `cut` to reorder or extract columns from a `sort-bed`-sorted `sample.bed` to put the score column into the correct fifth column, whichever column contains the score value you're expecting.

For more information on the quasi-semi-official BED specification: https://github.com/samtools/hts-specs/blob/master/BEDv1.pdf

I'll close this issue up, but if you still run into problems with sorted BED data that have identifier and score data in the expected columns, where the output is not expected, please follow up and I'll try to help.

**Comment by pdeven** [comment]
thanks @alexpreynolds  and @rsandstromUW  for the speedy Reply. I will check the no `--max` method
