### ISSUE TITLE
starch/unstarch produces error when --gzip compression is applied to empty (0-byte) bed file 

### ISSUE THREAD

**Issue by bgulko** [bedops/bedops#284]
This was addressed in 2.3.0 according to release notes (October 2, 2013). Indeed, as of 2.4.40, no issue appears with default bzip2 based compression. However, under 2.4.40, for Ubuntu 22.04 (LTS) linux, it seems to be present for gzip based compression (default is now bgzip2).

To Reproduce:

# create 0 byte bed.
$touch a.bed

# starch - no errors
$starch --gzip a.bed > a.gz.bed.starch
$starch --bzip2 a.bed > a.bz.bed.starch

# demonstrate no error for bgzip2 - based starch
$unstarch a.bz.bed.starch

# demonstrates error for gzip - reported to stderr
$ unstarch a.gz.bed.starch
ERROR: Z-stream suffered data error
ERROR: Backend extraction failed (gzip)

**Comment by bgulko** [comment]
@alexpreynolds **Thanks** for taking this on, Alex! It is a small issue and I have worked around it by using a bash function (below) which replaced gzip with bzip2 for 0 length files. Finding it was a pain. I usually use gzip in starch for light compression of files used frequently, or bzip2 compression for archival storage. As with the 2.3.0 notes, this was buried in a pipeline and broke the pipeline when 0 bed results were generated. Addressing the underlying issue will remove complexity from the pipeline. Thanks again!
check_starch() {
  local f_name="${1}"
  if [[ ! -s "${f_name}" ]]; then return; fi
  if [[ "${f_name##*.}" != "starch" ]]; then return; fi
  s_err=$( ( unstarch"${f_name}" | head -1 >> /dev/null ) 2>&1 )
  if [[ "${s_err}" != "" ]]; then
    echo -n "" | starch --bzip2 - > "${f_name}"
  fi
}
--Brad

**Comment by alexpreynolds** [comment]
Patched in commit 917dc677 (`v2p4p42` branch). Behavior of `unstarch --gzip` now matches that of `unstarch --bzip2`.

I'm still working on other patches for v2p4p42, so I'm not sure when this will go out to a main release, but hopefully soon. The patch is available in this branch now, if you need this sooner. Compilation instructions are available at: https://bedops.readthedocs.io/en/latest/content/installation.html#installation-via-source-code

Thanks for the bug report. I'll close this up for now. Please feel free to follow up if you still have issues.
