### ISSUE TITLE
Add bedmap --wmean option and documentation

### ISSUE THREAD

**Issue by sjneph** [bedops/bedops#51]
add weighted average option as requested by the community.

**Comment by bvernot** [comment]
Did this ever get added?  I don't see it in the current version of bedmap.

**Comment by sjneph** [comment]
No, it's not there.  I saw a couple of different ways that folks might want this implemented, and it was a little ugly when --range X is thrown into the mix (similar to --bases and --bases-uniq).
We can add it.  My first thought is:
SUM-OVER-MAPPED-ELEMENTS{ (num-bases-in-overlap)/(num-bases-in-map-element) * score-map-element }

The geometric mean could be another option.

Do you have a different idea of what weighted-mean means?

I think the --range thing can be explained easily enough and we should add this feature.

**Comment by sjneph** [comment]
--wmean has been added to v2p4p21 of bedmap, see 486e4eeb3a554872aa5f5d696c8ae3c95c3e609d
